using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Assets.VirtualMachineRunner
{
	public enum OtherType
	{
		OutsideRoom,
		IntersectBoundary,
		GameStart,
		GameEnd,
		RoomStart,
		RoomEnd,
		NoMoreLives,
		AnimationEnd,
		EndOfPath,
		NoMoreHealth,
		User0,
		User1,
		User2,
		User3,
		User4,
		User5,
		User6,
		User7,
		User8,
		User9,
		User10,
		User11,
		User12,
		User13,
		User14,
		User15,
		User16,
		OutsideView0,
		OutsideView1,
		OutsideView2,
		OutsideView3,
		OutsideView4,
		OutsideView5,
		OutsideView6,
		OutsideView7,
		BoundaryView0,
		BoundaryView1,
		BoundaryView2,
		BoundaryView3,
		BoundaryView4,
		BoundaryView5,
		BoundaryView6,
		BoundaryRoom7,
		AnimationUpdate,
		AnimationEvent,
		AsyncImageLoaded,
		AsyncSoundLoaded,
		AsyncHTTP,
		AsyncDialog,
		AsyncIAP,
		AsyncCloud,
		AsyncNetworking,
		AsyncSteam,
		AsyncSocial,
		AsyncPushNotification,
		AsyncSaveAndLoad,
		AsyncAudioRecording,
		AsyncAudioPlayback,
		AsyncSystem
	}
}
