using System;
using System.Collections.Generic;
using System.IO;
using OBJECT_SCRIPTS;
using OBJECT_SCRIPTS.DOOR;
using UnityEngine;
namespace Assets
{
	public partial class GamemakerObject
	{
		public obj_mainchara obj_mainchara => FindObjectOfType<obj_mainchara>();
		public dynamic i;
		public dynamic j;
		public dynamic q;
		public dynamic spellid;
		public dynamic spellname;
		public dynamic spellnameb;
		public dynamic spelldescb;
		public dynamic spelldesc;
		public dynamic cost;
		public dynamic spellusable;
		public dynamic spelltarget;
		public dynamic spellanim;
		public dynamic spelltext;
		public dynamic usable;
		public dynamic itemid;
		public dynamic itemnameb;
		public dynamic itemdescb;
		public dynamic value;
		public dynamic itemtarget;
		public dynamic roomchoice;
		public dynamic menu_go;
		public dynamic quit_timer;
		public dynamic keyboard_active;
		public dynamic gamepad_active;
		public dynamic gamepad_check_timer;
		public dynamic gamepad_id;
		public dynamic axis_value;
		public dynamic fullscreen_toggle;
		public dynamic window_center_toggle;
		public dynamic screenshot_number;
		public dynamic display_height;
		public dynamic display_width;
		public dynamic window_size_multiplier;
		public dynamic _ww;
		public AudioSource _xsndinstance;
		public dynamic SONG_THAT_EMERGES_FROM_A_SLEEPING_DOG;
		public dynamic EVENT;
		public dynamic TIMER;
		public dynamic HEARTMADE;
		public dynamic HSINER;
		public dynamic OBMADE;
		public dynamic ALREADY;
		public dynamic TRUE_ALREADY;
		public dynamic SKIPBUFFER;
		public dynamic FADED;
		public dynamic FADEFACTOR;
		public dynamic FADEUP;
		public dynamic OB_DEPTH;
		public dynamic obacktimer;
		public dynamic OBM;
		public dynamic WHITEFADE;
		public dynamic W;
		public dynamic SOUL;
		public dynamic skipme;
		public dynamic textsound;
		public dynamic charline;
		public dynamic originalcharline;
		public dynamic hspace;
		public dynamic vspace;
		public dynamic rate;
		public dynamic mycolor;
		public dynamic myfont;
		public dynamic shake;
		public dynamic special;
		public dynamic skippable;
		public dynamic automash_timer;
		public dynamic f;
		public dynamic autoaster;
		public dynamic pos;
		public dynamic lineno;
		public dynamic aster;
		public dynamic halt;
		public dynamic xcolor;
		public dynamic wxskip;
		public dynamic msgno;
		public dynamic first_alarm;
		public dynamic firstnoise;
		public dynamic noiseskip;
		public dynamic formatted;
		public dynamic colorchange;
		public dynamic fontchange;
		public dynamic sound_played;
		public dynamic writingx;
		public dynamic writingy;
		public dynamic dialoguer;
		public obj_smallface smallface;
		public dynamic faced;
		public dynamic facedever;
		public dynamic facer;
		public dynamic siner;
		public dynamic specfade;
		public dynamic specx = new double[7];
		public dynamic specy = new double[7];
		public dynamic mystring;
		public dynamic nstring = new string[100];
		public dynamic length;
		public dynamic getchar;
		public dynamic nextchar;
		public dynamic button1;
		public dynamic button2;
		public dynamic button3;
		public dynamic playtextsound;
		public dynamic play;
		public dynamic playcheck;
		public dynamic textscale;
		public dynamic charpos = new int[3];
		public dynamic remspace;
		public dynamic remchar;
		public dynamic linecount;
		public dynamic stringmax;
		public dynamic textalignment;
		public dynamic skip;
		public dynamic thischar;
		public dynamic nextchar2;
		public dynamic accept;
		public dynamic wx;
		public dynamic wy;
		public dynamic n;
		public dynamic mychar;
		public dynamic fam;
		public dynamic ddir;
		public dynamic con;
		public dynamic t;
		public dynamic m;
		public dynamic tmax;
		public dynamic momentum;
		public dynamic xs;
		public dynamic stringpos;
		public dynamic part;
		public dynamic partstring;
		public dynamic type;
		public dynamic active;
		public dynamic finished;
		public dynamic getrid;
		public dynamic writergod;
		public dynamic nowdir;
		public dynamic facealpha;
		public dynamic mouthmove;
		public dynamic mouthtimer;
		public dynamic face_index;
		public dynamic nowface;
		public dynamic facechange;
		public dynamic buffer;
		public dynamic face;
		public dynamic PITCH;
		public DEVICE_OBACK_4 DV;
		public dynamic alpha;
		public dynamic xstretch;
		public dynamic ystretch;
		public dynamic o_insurance;
		public dynamic OBSPEED;
		public dynamic b_insurance;
		public DEVICE_GONERMAKER GM;
		public dynamic HEAD;
		public dynamic BODY;
		public dynamic LEGS;
		public dynamic HEADMAX;
		public dynamic BODYMAX;
		public dynamic LEGSMAX;
		public dynamic PART = new int[3];
		public dynamic PARTMAX = new int[3];
		public dynamic s;
		public dynamic offx;
		public dynamic movetimer;
		public dynamic PARTX = new int[3];
		public dynamic IDEALX = new int[3];
		public bool[] LOCK = new bool[3];
		public dynamic sy = new int[3];
		public dynamic flashtimer;
		public dynamic midscreenx;
		public dynamic midscreeny;
		public dynamic STEP;
		public dynamic FINISH;
		public dynamic ONEBUFFER;
		public dynamic FADEBUFFER;
		public dynamic CANCEL;
		public dynamic initx;
		public dynamic inity;
		public dynamic NAMEFADE;
		public dynamic FA;
		public dynamic k;
		public dynamic img;
		public dynamic s_size;
		public dynamic NAMEFADE_COMPLETE;
		public dynamic CURX;
		public dynamic CURY;
		public dynamic XMAX;
		public dynamic YMAX;
		public dynamic NAME = new string[10, 10];
		public dynamic NAMEX = new int[10, 10];
		public dynamic NAMEY = new int[10, 10];
		public dynamic PLAYERNAMEY;
		public dynamic TYPE;
		public dynamic NAMESTRING;
		public dynamic STRINGMAX;
		public dynamic yoff;
		public dynamic xoff;
		public dynamic LANGSUBTYPE;
		public dynamic HEARTX;
		public dynamic HEARTY;
		public dynamic DRAWHEART;
		public dynamic TWOBUFFER;
		public dynamic fadebuffer;
		public dynamic xfade;
		public dynamic HEARTDIFF;
		public dynamic ERASE;
		public dynamic choice;
		public dynamic GMSINE;
		public dynamic CHOICE;
		public dynamic JA_XOFF;
		public dynamic gmx;
		public dynamic gmy;
		public dynamic FN_2;
		public dynamic FOUND;
		public dynamic FN;
		public dynamic FN_3;
		public dynamic p;
		public AudioSource loop1;
		public AudioSource loop2;
		public dynamic thismarker;
		public dynamic wallwindow;
		public dynamic d;
		public dynamic cur_jewel;
		public dynamic free;
		public dynamic xxx;
		public dynamic yyy;
		public dynamic writer;
		public dynamic side;
		public dynamic xx;
		public dynamic yy;
		public dynamic myface;
		public dynamic textbox_width;
		public dynamic textbox_height;
		public dynamic cutscene;
		public dynamic wd;
		public dynamic ht = new int[4];
		public dynamic initwd;
		public dynamic initht;
		public dynamic battlemode;
		public dynamic becamebattle;
		public dynamic battlealpha;
		public dynamic fun;
		public dynamic autorun;
		public dynamic bg;
		public dynamic stepping;
		public dynamic stepped;
		public obj_overworldheart battleheart;
		public dynamic darkmode;
		public dynamic press_l;
		public dynamic press_r;
		public dynamic press_d;
		public dynamic press_u;
		public dynamic px;
		public dynamic py;
		public dynamic wallcheck;
		public dynamic wspeed;
		public dynamic bwspeed;
		public dynamic run;
		public dynamic runtimer;
		public dynamic subxspeed;
		public dynamic subyspeed;
		public dynamic subx;
		public dynamic suby;
		public dynamic walkanim;
		public dynamic walkbuffer;
		public dynamic walktimer;
		public dynamic dsprite;
		public dynamic rsprite;
		public dynamic usprite;
		public dynamic lsprite;
		public dynamic onebuffer;
		public dynamic twobuffer;
		public dynamic threebuffer;
		public dynamic mywidth;
		public dynamic myheight;
		public dynamic nowx;
		public dynamic nowy;
		public dynamic nopress;
		public dynamic bkx;
		public dynamic bky;
		public dynamic bkxy;
		public dynamic jelly;
		public dynamic pressdir;
		public dynamic xmeet;
		public dynamic ymeet;
		public dynamic xymeet;
		public dynamic g;
		public dynamic mvd;
		public dynamic runmove;
		public dynamic walk;
		public dynamic thisinteract;
		public dynamic interactedobject;
		public dynamic myinteract;
		public GamemakerObject mydialoguer;
		public dynamic facing;
		public dynamic saved;
		public dynamic selnoise;
		public dynamic movenoise;
		public dynamic currentmenu;
		public dynamic currentspot;
		public dynamic dontthrow;
		public dynamic moveyy;
		public dynamic weaponname;
		public dynamic armorname = new string[12];
		public dynamic nextlevel;
		public dynamic tempsaid;
		public dynamic haveit;
		public dynamic itemcount;
		public dynamic maxedout;
		public dynamic recovered;
		public dynamic filechoicebk2;
		public dynamic file;
		public dynamic myfileid;
		public dynamic read;
		public dynamic tempvar;
		public dynamic shine;
		public dynamic charcon;
		public dynamic talked;
		public dynamic depthcancel;
		public dynamic normalanim;
		public dynamic remanimspeed;
		public dynamic touched;
		public dynamic fadespeed;
		public dynamic height;
		public dynamic sx;
		public dynamic shadow;
		public dynamic candyflag;
		public dynamic timer;
		public dynamic entrance;
		public dynamic rem_facing;
		public dynamic facing_timer;
		public dynamic candytree;
		public dynamic pie;
		public dynamic songplayed;
		public dynamic maxm;
		public dynamic doorimg;
		public dynamic doorsolid;
		public dynamic doorevent;
		public dynamic door_door;
		public dynamic finalsolid;
		public dynamic block = new dynamic[3];
		public dynamic th;
		public dynamic chairsolid;
		public dynamic blackmarker;
		public dynamic setdepth;
		public dynamic num;
		public dynamic colortxt;
		public dynamic ch;
		public dynamic prevalpha = new double[20];
		public dynamic prevwx = new double[20];
		public dynamic prevwy = new double[20];
		public dynamic prevstringmax = new int[20];
		public dynamic prevhspace = new int[20];
		public dynamic prevlinecount = new int[20];
		public dynamic prevvspace = new int[20];
		public dynamic carcon;
		public dynamic drawwave;
		public dynamic dhaver;
		public dynamic v;
		public dynamic vx;
		public dynamic vy;
		public dynamic myd;
		public dynamic c = new dynamic[3];
		public dynamic dd;
		public obj_panner panner;
		public dynamic panx;
		public dynamic pany;
		public dynamic panmax;
		public dynamic pantimer;
		public dynamic ckx;
		public dynamic cky;
		public dynamic ctx;
		public dynamic cty;
		public dynamic fade;
		public obj_persistentfadein fade2;
		public dynamic car;
		public dynamic catty;
		public dynamic cattydad;
		public dynamic bratty;
		public dynamic froggit;
		public dynamic qc;
		public dynamic bear;
		public dynamic undyne;
		public obj_persistentfadein pf;
		public dynamic ran;
		public dynamic dex;
		public dynamic tsouth;
		public dynamic teast;
		public dynamic door;
		public dynamic alphys;
		public obj_doorB doorb;
		public dynamic sunset;
		public obj_npc_facing alphys_facing;
		public dynamic door_readable;
		public dynamic dtsprite;
		public dynamic rtsprite;
		public dynamic ltsprite;
		public dynamic utsprite;
		public dynamic dfacing;
		public dynamic ourcase;
		public dynamic depthbonus;
		public dynamic eggmake;
		public dynamic egcon;
		public dynamic egtimer;
		public dynamic egg;
		public dynamic sus;
		public dynamic choicer;
		public dynamic choicetotal;
		public dynamic canchoose;
		public dynamic dar;
		public dynamic add;
		public dynamic mychoice;
		public dynamic choiced;
		public dynamic camera;
		public dynamic shakespeed;
		public dynamic shakesign;
		public dynamic shakex;
		public dynamic shakey;
		public dynamic permashake;
		public dynamic camerax;
		public dynamic cameray;
		public dynamic chalksound;
		public dynamic choosetimer;
		public dynamic interact;
		public dynamic scon;
		public dynamic open;
		public dynamic xsin;
		public dynamic amt;
		public dynamic wt;
		public dynamic papetimer;
		public dynamic papeno;
		public dynamic papei;
		public dynamic papefall;
		public dynamic papeshake;
		public dynamic grav;
		public dynamic bgdraw;
		public dynamic bgamt;
		public dynamic rate_alpha;
		public dynamic after_x;
		public obj_fallpaper[] pape = new obj_fallpaper[22];
		public dynamic remxx;
		public AudioSource pape_sfx;
		public dynamic IDEALY;
		public dynamic waketimer;
		public dynamic canclick;
		public dynamic chartotal;
		public dynamic havechar = new bool[3];
		public dynamic _rreturn;
		public dynamic nodialogue;
		public dynamic tname;
		public dynamic coord;
		public dynamic ini_ex;
		public dynamic level;
		public dynamic love;
		public dynamic time;
		public dynamic roome;
		public dynamic endme;
		public dynamic minutes;
		public dynamic seconds;
		public dynamic roomname;
		public dynamic heartsprite;
		public dynamic _speed;
		public dynamic BGMADE;
		public dynamic BG_ALPHA;
		public dynamic BG_SINER;
		public dynamic COL_A;
		public dynamic COL_B;
		public dynamic COL_PLUS;
		public dynamic BGSINER;
		public dynamic BGMAGNITUDE;
		public dynamic ANIM_SINER;
		public dynamic ANIM_SINER_B;
		public dynamic TRUE_ANIM_SINER;
		public dynamic MENU_NO;
		public dynamic MENUCOORD = new int[8];
		public dynamic XL;
		public dynamic YL;
		public dynamic YS;
		public dynamic HEARTXCUR;
		public dynamic HEARTYCUR;
		public dynamic MOVENOISE;
		public dynamic SELNOISE;
		public dynamic BACKNOISE;
		public dynamic DEATHNOISE;
		public dynamic THREAT;
		public dynamic TEMPMESSAGE;
		public dynamic MESSAGETIMER;
		public dynamic FILE = new int[3];
		public dynamic TIME = new int[3];
		public dynamic PLACE = new string[3];
		public dynamic LEVEL = new int[3];
		public dynamic TIME_STRING = new string[3];
		public dynamic INITLANG = new int[3];
		public dynamic TIME_SECONDS_TOTAL = new int[3];
		public dynamic TIME_SECONDS_STRING = new string[3];
		public dynamic TIME_SECONDS = new int[3];
		public dynamic TIME_MINUTES = new int[3];
		public dynamic _NEWNAME;
		public dynamic _NEWTIME;
		public dynamic _NEWROOM;
		public dynamic _NEWLEVEL;
		public dynamic CONT_THIS;
		public dynamic PREV_MENU;
		public dynamic BOX_X1;
		public dynamic BOX_Y1;
		public dynamic BOX_X2;
		public dynamic BOX_Y2;
		public dynamic SELTEXT_A;
		public dynamic SELTEXT_B;
		public dynamic SELTEXT_C;
		public dynamic __txtcolor__;
		public dynamic CANCELTEXT;
		public dynamic COPYTEXT;
		public dynamic ERASETEXT;
		public dynamic LANGUAGETEXT;
		public dynamic TEMPCOMMENT;
		public dynamic readval;
		public dynamic filechoicebk;
		public dynamic __loadedroom;
		public dynamic wobbled;
		public dynamic collide;
		public dynamic collidetimer;
		public dynamic cancollide;
		public dynamic collider;
		public dynamic slidetimer;
		public dynamic abovey;
		public dynamic bust;
		public dynamic slide_noise;
		public dynamic dust;
		public dynamic tilearray;
		public dynamic s2;
		public dynamic dbullet;
		public dynamic tile_fade;
		public dynamic fadeplease;
		public dynamic tile_layer_amount;
		public dynamic alpha_changed;
		public dynamic cur_alpha;
		public dynamic dir;
		public dynamic blushtimer;
		public dynamic target;
		public dynamic usprite_blush;
		public dynamic dsprite_blush;
		public dynamic rsprite_blush;
		public dynamic lsprite_blush;
		public dynamic parent;
		public dynamic pd;
		public dynamic pr;
		public dynamic pl;
		public dynamic pu;
		public dynamic remx = new double[26];
		public dynamic remy = new double[26];
		public dynamic moved;
		public dynamic distfrommcx;
		public dynamic distfrommcy;
		public dynamic mytarget;
		public dynamic chartarget;
		public dynamic tdamage;
		public dynamic damage;
		public dynamic hpdiff;
		public dynamic delaytimer;
		public dynamic killactive;
		public dynamic doomtype;
		public dynamic dmgnoise;
		public dynamic dmgwriter;
		public dynamic hpi;
		public dynamic gameover;
		public dynamic abletotarget;
		public dynamic spec;
		public dynamic delay;
		public dynamic bounces;
		public dynamic stretch;
		public dynamic stretchgo;
		public dynamic lightf;
		public dynamic lightb;
		public dynamic lightg;
		public dynamic kill;
		public dynamic killtimer;
		public dynamic specialmessage;
		public dynamic vstart;
		public dynamic flip;
		public dynamic message;
		public dynamic remdamage;
		public dynamic remtarget;
		public dynamic ti;
		public dynamic d_cancel;
		public dynamic hurt;
		public dynamic hurttimer;

		public double chartimer;
		public double tp;
		public bool selectnoise;
		public int upbuffer;
		public int downbuffer;
		public int hold_up;
		public int hold_down;
		public int dograndom;
		public double atalk;
		public int bcolor;
		public double tpy;
		public double bp;
		public double bpy;
		public double[] mmy = new double[3];
		public double slmxx;
		public double slmyy;
		public double s_siner;
		public double menusiner;
		public dynamic pagemax = new double[3];
		public double getmusvol;
		public double curvol;
		public int[] hpcolor = new int[3];
		public double tpoff;
		public double bpoff;
		public int drawchar;
		public int deschaver;
		public int off;
		public double spritemx;
		public string[] msprite = new string[5];
		public string audvol;
		public string musvol;
		public string runoff;
		public string flashoff;
		public string shakeoff;
		public string fullscreenoff;
		public string[] function = new string[9];
		public int control_select_con;
		public double control_flash_timer;
		public dynamic charcolor = new int[3];
		public int gc;
		public int xchunk;
		public int[] btc = new int[5];
		public int spare_glow;
		public int sglowi;
		public bool pacify_glow;
		public int b_offset;
		public double myxx;
		public int close;
		public string weaponnametemp;
		public string weapondesctemp;
		public dynamic wmessage2temp;
		public dynamic wmessage3temp;
		public dynamic weaponattemp;
		public dynamic weapondftemp;
		public dynamic weaponmagtemp;
		public dynamic weaponboltstemp;
		public dynamic weaponstyletemp;
		public dynamic weapongrazeamttemp;
		public dynamic weapongrazesizetemp;
		public dynamic weaponchar1temp;
		public dynamic weaponchar2temp;
		public dynamic weaponchar3temp;
		public dynamic weaponabilitytemp;
		public dynamic weaponabilityicontemp;
		public dynamic weaponicontemp;
		public dynamic weapondesc = new dynamic[12];
		public dynamic wmessage2 = new dynamic[12];
		public dynamic wmessage3 = new dynamic[12];
		public dynamic weaponat = new dynamic[12];
		public dynamic weapondf = new dynamic[12];
		public dynamic weaponmag = new dynamic[12];
		public dynamic weaponbolts = new dynamic[12];
		public dynamic weaponstyle = new dynamic[12];
		public dynamic weapongrazeamt = new dynamic[12];
		public dynamic weapongrazesize = new dynamic[12];
		public dynamic weaponchar1 = new dynamic[12];
		public dynamic weaponchar2 = new dynamic[12];
		public dynamic weaponchar3 = new dynamic[12];
		public dynamic weaponvalue = new dynamic[12];
		public dynamic weaponability = new dynamic[12];
		public dynamic weaponabilityicon = new dynamic[12];
		public dynamic weaponicon = new dynamic[12];
		public dynamic armornametemp;
		public dynamic armordesctemp;
		public dynamic amessage2temp;
		public dynamic amessage3temp;
		public dynamic armorattemp;
		public dynamic armordftemp;
		public dynamic armormagtemp;
		public dynamic armorboltstemp;
		public dynamic armorgrazeamttemp;
		public dynamic armorgrazesizetemp;
		public dynamic armorchar1temp;
		public dynamic armorchar2temp;
		public dynamic armorchar3temp;
		public dynamic armorabilitytemp;
		public dynamic armorabilityicontemp;
		public dynamic armoricontemp;
		public dynamic armordesc = new dynamic[12];
		public dynamic amessage2 = new dynamic[12];
		public dynamic amessage3 = new dynamic[12];
		public dynamic armorat = new dynamic[12];
		public dynamic armordf = new dynamic[12];
		public dynamic armormag = new dynamic[12];
		public dynamic armorbolts = new dynamic[12];
		public dynamic armorstyle = new dynamic[12];
		public dynamic armorgrazeamt = new dynamic[12];
		public dynamic armorgrazesize = new dynamic[12];
		public dynamic armorchar1 = new dynamic[12];
		public dynamic armorchar2 = new dynamic[12];
		public dynamic armorchar3 = new dynamic[12];
		public dynamic armorvalue = new dynamic[12];
		public dynamic armorability = new dynamic[12];
		public dynamic armorabilityicon = new dynamic[12];
		public dynamic armoricon = new dynamic[12];
		public dynamic charweaponname = new dynamic[4];
		public dynamic charweapondesc = new dynamic[4];
		public dynamic charweaponat = new dynamic[4];
		public dynamic charweapondf = new dynamic[4];
		public dynamic charweaponmag = new dynamic[4];
		public dynamic charweaponbolts = new dynamic[4];
		public dynamic charweaponstyle = new dynamic[4];
		public dynamic charweapongrazeamt = new dynamic[4];
		public dynamic charweapongrazesize = new dynamic[4];
		public dynamic charweaponability = new dynamic[4];
		public dynamic charweaponabilityicon = new dynamic[4];
		public dynamic charweaponicon = new dynamic[4];

		public dynamic chararmor1name = new dynamic[4];
		public dynamic chararmor1desc = new dynamic[4];
		public dynamic chararmor1at = new dynamic[4];
		public dynamic chararmor1df = new dynamic[4];
		public dynamic chararmor1mag = new dynamic[4];
		public dynamic chararmor1bolts = new dynamic[4];
		public dynamic chararmor1style = new dynamic[4];
		public dynamic chararmor1grazeamt = new dynamic[4];
		public dynamic chararmor1grazesize = new dynamic[4];
		public dynamic chararmor1ability = new dynamic[4];
		public dynamic chararmor1abilityicon = new dynamic[4];
		public dynamic chararmor1icon = new dynamic[4];

		public dynamic chararmor2name = new dynamic[4];
		public dynamic chararmor2desc = new dynamic[4];
		public dynamic chararmor2at = new dynamic[4];
		public dynamic chararmor2df = new dynamic[4];
		public dynamic chararmor2mag = new dynamic[4];
		public dynamic chararmor2bolts = new dynamic[4];
		public dynamic chararmor2style = new dynamic[4];
		public dynamic chararmor2grazeamt = new dynamic[4];
		public dynamic chararmor2grazesize = new dynamic[4];
		public dynamic chararmor2ability = new dynamic[4];
		public dynamic chararmor2abilityicon = new dynamic[4];
		public dynamic chararmor2icon = new dynamic[4];

		public dynamic w;
		public dynamic healx;
		public dynamic healtext;

		public dynamic abovemaxhp;
		public dynamic belowzero;
		public dynamic hltarget;
		public dynamic _curhp;

		public dynamic itemdesc = new dynamic[12];

		public dynamic _gc;
		public dynamic ralpos;
		public dynamic suspos;
		public dynamic talkx;
		public dynamic itemcomment;
		public dynamic reviveamt;
		public dynamic m_quit;
		public dynamic sndbuffer;
		public dynamic se_select;
		public dynamic muschange;
		public dynamic sndchange;
		public dynamic audchange;
		public dynamic sm;
		public dynamic yheart;
		public dynamic xheart;
		public dynamic keyitemid;
		public dynamic tempkeyitemusable;
		public dynamic tempkeyitemname;
		public dynamic tempkeyitemdesc;
		public dynamic[] keyitemname = new dynamic[12];
		public dynamic[] keyitemusable = new dynamic[12];
		public dynamic[] keyitemdesc = new dynamic[12];
		public dynamic sndplay;
		public dynamic total;
		public dynamic[] eye = new dynamic[3];
		public dynamic glass;
		public dynamic done;
		public dynamic partysus;
		public dynamic darksus;
		public dynamic suspeed;
		public dynamic darksus2;
		public dynamic thisremx;
		public dynamic thisremy;
		public dynamic speedtimer;
		public dynamic news;
		public dynamic ss;
		public dynamic[] scrollspeed = new dynamic[7];
		public dynamic gg;
		public dynamic aftercon;
		public dynamic susie;
		public dynamic lancer;
		public dynamic[] b = new dynamic[2];
		public dynamic[] bdir = new dynamic[2];
		public dynamic _wd;
		public dynamic _ht;
		public dynamic _vx;
		public dynamic _vy;
		public dynamic afterimage;
		public dynamic a;
		public dynamic darkamt;
		public dynamic homing;
		public dynamic intensity;
		public dynamic[] sidespade = new dynamic[2];
		public dynamic radius;
		public dynamic dirx;
		public dynamic diry;
		public dynamic fallspade;
		public dynamic alarmamt;
		public dynamic slow_bonus;
		public dynamic vvalue;
		public dynamic fvalue;
		public dynamic cameracon;
		public dynamic ever;
		public dynamic seiz;
		public dynamic slidesfx;
		public dynamic block1;
		public dynamic block2;
		public dynamic shifted;
		public dynamic fo;
		public dynamic rd;
		public dynamic runamt;
		public dynamic rflip;
		public dynamic wr;
		public dynamic r;
		public dynamic remfc;
		public dynamic d_add;
		public dynamic chx;
		public dynamic chy;
		public dynamic hx;
		public dynamic hy;
		public dynamic[] textposx = new dynamic[4];
		public dynamic[] textposy = new dynamic[4];
		public dynamic candraw;
		public dynamic wwx;
		public dynamic wwy;
		public dynamic textx;
		public dynamic texty;
		public dynamic[] heartposx = new dynamic[4];
		public dynamic[] heartposy = new dynamic[4];
		public dynamic contimer;
		public dynamic ytimer;
		public dynamic xtimer;
		public dynamic fadecolor;
		public dynamic chunkfade;
		public dynamic chunkamt;
		public dynamic border;
		public dynamic pic;
		public dynamic textimer;
		public dynamic ingame;
		public dynamic skipped;
		public dynamic skiptimer;
		public dynamic c_chunkamt;
		public dynamic con_alph;
		public dynamic alph;
		public dynamic l;
		public dynamic ex;
		public dynamic maxamt;
		public dynamic r2;
		public dynamic r3;
		public dynamic count;
		public dynamic fightcon;
		public dynamic counttimer;
		public dynamic af;
		public dynamic wp;
		public dynamic wp2;
		public dynamic victory;
		public dynamic victoried;
		public dynamic skipvictory;
		public obj_writer battlewriter;
		public dynamic lbuffer;
		public dynamic rbuffer;
		public int[,] tempitem = new int[13, 4];
		public int itempage;
		public dynamic laznoise;
		public dynamic damagenoise;
		public dynamic grazenoise;
		public dynamic intro;
		public dynamic reset;
		public dynamic timeron;
		public dynamic noreturn;
		public dynamic techwon;
		public dynamic tu;
		public dynamic hptarget;
		public dynamic healamt;
		public dynamic dmgwr;
		public dynamic attacked = new bool[3];
		public dynamic acting;
		public dynamic moveswapped;
		public dynamic bikeflip;
		public dynamic becomeflash;
		public dynamic turnt;
		public dynamic turns;
		public dynamic talktimer;
		public dynamic talkmax;
		public dynamic state;
		public dynamic flash;
		public dynamic fsiner;
		public dynamic hurtshake;
		public dynamic mywriter;
		public dynamic actcon;
		public dynamic acttimer;
		public dynamic mercymod;
		public dynamic maxmercy;
		public dynamic warned;
		public dynamic compliment;
		public dynamic compliment_just;
		public dynamic attacks;
		public dynamic dodgetimer;
		public dynamic candodge;
		public int myself;
		public dynamic dodgeamt;
		public dynamic thissprite;
		public dynamic spareanim;
		public dynamic sparedsprite;
		public dynamic _amt_add;
		public dynamic _violenced;
		public dynamic _spared;
		public dynamic _pacified;
		public dynamic d_i;
		public dynamic chara;
		public dynamic points = new int[3];
		public dynamic attacktimer;
		public dynamic combatdarken;
		public dynamic darkentimer;
		public dynamic darkify;
		public dynamic index;
		public dynamic specdraw;
		public dynamic is_auto_susie;
		public dynamic normalsprite;
		public dynamic idlesprite;
		public dynamic actreadysprite;
		public dynamic actsprite;
		public dynamic hurtsprite;
		public dynamic defendsprite;
		public dynamic attackreadysprite;
		public dynamic attacksprite;
		public dynamic itemsprite;
		public dynamic itemreadysprite;
		public dynamic spellreadysprite;
		public dynamic spellsprite;
		public dynamic defeatsprite;
		public dynamic victorysprite;
		public dynamic victoryanim;
		public dynamic actframes;
		public dynamic victoryframes;
		public dynamic defendframes;
		public dynamic itemframes;
		public dynamic attackframes;
		public dynamic attackspeed;
		public dynamic actreturnframes;
		public dynamic spellframes;
		public dynamic hurtindex;
		public dynamic defendtimer;
		public dynamic itemed;
		public dynamic cancelattack;
		public dynamic dm;
		public dynamic attack;
		public dynamic ls;
		public dynamic anim;
		public dynamic thistarget;
		public dynamic spell;
		public dynamic caster;
		public dynamic star = new dynamic[15];
		public dynamic tsiner;
		public double apparent;
		public double current;
		public dynamic change;
		public dynamic changetimer;
		public dynamic red;
		public dynamic redtimer;
		public dynamic flashsiner;
		public dynamic tamt;
		public dynamic maxed;
		public dynamic theight;
		public dynamic theight2;
		public dynamic victortimer;

		public dynamic darken;

		public dynamic prevturn;

		public dynamic charcan;

		public string[,] tempitemnameb = new string[12,4];
		public string[,] tempitemdescb = new string[12, 4];
		public int[,] tempitemvalue = new int[12, 4];
		public bool[,] tempitemusable = new bool[12, 4];

		public int maxtimer;
		public int growcon;
		public int fullgrow;
		public int keep;
		public int megakeep;
		public int growth;

		public double lborder;
		public double rborder;
		public double uborder;
		public double dborder;

		public int fightphase;
		public dynamic cango;
		public int spellcoord;

		public int thisenemy;

		public int actcoord;

		public bool canpress;

		public bool mercydraw;
		public bool tireddraw;
		public int mnamecolor1;
		public int mnamecolor2;
		public int aqcolor;
		public int namewidth;
		public int mercyamt;

		public int page;
		public int icx;
		public int icy;
		public int thiscost;

		public bool cant;
		public int chartime;
		public int charoffset;
		public int xoffset;
		public int yoffset;
		public bool drawsus;
		public bool drawral;
		public int susblend;
		public int ralblend;

		public int jp_string_lengthtest_act;
		public double jp_string_xscale;

		public dynamic bike;

		public int rr;

		public dynamic myblcon;

		public bool fastmode;
		public bool goahead;
		public int linespeed;
		public int linex;
		public bool spelluse;
		public int[] spelldelay = new int[3];
		public int maxdelay;
		public int maxdelaytimer;
		public int xyz;

		public int[] charitem = new int[3];
		public int[] charspell = new int[3];

		public double fadeamt;
		public int fakefade;
		public int[] boltcolor = new int[3];
		public int imagetimer;
		public int posttimer;
		public int timermax;
		public int[] boltorder = new int[3];
		public int boltgap;
		public int boltspeed;
		public int boltx;
		public int[] pressbuffer = new int[4];
		public int[] charbolt = new int[3];
		public int bolttotal;
		public int boltxoff;
		public int method;
		public int boltnum;
		public int[] boltuse = new int[3];
		public int[] boltchar = new int[3];
		public int lastbolt;
		public int diff;
		public int[] boltalive = new int[3];
		public int[] boltred = new int[3];
		public int[,] boltframe = new int[3,3];
		public bool haveauto;
		public bool autoed;
		public int fullbox;
		public int[] boltcount = new int[3];
		public int offset;
		public double boltalpha;

		public int qualifybolt;
		public int topclose;
		public dynamic burstbolt;
		public int dualbolt;
		public int dualboltid;
		public int bc;

		public int maxindex;
		public bool critical;

		public int hurtamt;

		public int burst;
		public int shift;
		public double dist;
		public int flytime;

		public double distx;
		public double disty;

		public double fly;
		public int boundaryup;

		public int _temptarget;

		public bool grazed;
		public int grazepoints;
		public int timepoints;
		public int dont;
		public int inv;
		public int wall_destroy;

		public bool loop;
		public double lcon;
		public double ltimer;
		public int btimer;
		public int endcon;
		public int racecon;
		public double topy;
		public double bottomy;
		public double orx;
		public double ory;
		public double ang;
		public double shrinktimer;

		public dynamic bullet;

		public int s_moveup;
		public int rtimer;
		public double maxr;
		public dynamic honkimg;

		public int grazetimer;

		public double xrate;
		public double yrate;

		public obj_writer lastbattlewriter;

		public double siner2;
		public int destroy;

		public string input_name;

		public dynamic dummy;

		public bool noroom;

		public dynamic cs;

		public int hcon;

		public dynamic _mmm;

		public double movex;
		public double movey;
		public double movemax;
		public double xadd;
		public double yadd;

		public double pausetimer;

		public int alertcon;
		public double walk_index;
		public double targetx;
		public double targety;
		public int touchflag;
		public dynamic newme;
		public int alerttimer;
		public int facetimer;
		public int chasetype;
		public double pacetype;
		public int pacecon;
		public int pacecon2;
		public int pacetimer;
		public double moveradius;
		public double pacespeed;
		public bool frozen;
		public bool hadfrozen;
		public bool offscreen_frozen;
		public dynamic remspeed;
		public int myencounter;
		public string touchsprite;
		public bool cancelwalk;
		public bool eraser;
		public bool ignoresolid;
		public double xnext;
		public double ynext;

		public bool _offcamera;
		public double rightx;
		public double leftx;

		public int fliptimer;
		public string slidesprite;
		public AudioSource hnka;
		public AudioSource hnkb;
		public int copyhave;
		public dynamic cc = new dynamic[3];
		public obj_marker[] copy = new obj_marker[3];

		public bool tired;
		public int battlecancel;
		public bool nexttry;

		public dynamic dc;

		public dynamic defeatanim;

		public int difficulty;
		public int joker;
		public int made;
		public double miny;
		public double maxy;
		public double ratio;

		public dynamic bm;
		public dynamic bul = new dynamic[16];

		public double times;
		public double activetimer;
		public double futuredir;
		public GamemakerObject mybul;

		public int spelltimer;
		public int spellmax;
		public int spelltotal;
		public int castyet;
		public int re_castyet;

		public int[] _using = new int[3];
		public int[] gotspell = new int[3];
		public int[] gotitem = new int[3];
		public obj_writer spellwriter;

		public int _en;
		public int _j;
		public int spec_shard;
		public int[] shardtest = new int[3];
		public int manual;

		public int itemcoord;
		public int pacifycon;
		public GamemakerObject _pspell;
		public int fail;
		public int sparecon;
		public int flashcolor;

		public obj_afterimage ai;

		public int starcount;
		public int tone;
		public double neotone;
		public double maxwhite;

		public int record;
		public int tiletotal;
		public int funtotal;
		public int order;
		public int funbuffer;
		public bool stepnoise;
		public int wonamt;
		public int failtimer;
		public int failamt;
		public int wonmax;
		public int plotamt;
		public int failmax;
		public obj_marker[] spike1 = new obj_marker[3];
		public obj_marker[] spike2 = new obj_marker[3];
		public int shakecon;
		public int choice1;
		public int choice2;
		public int choice3;
		public int curtotal;
		public obj_glowtile tempid;
		public obj_glowtile[] tileid = new obj_glowtile[6];
		public int stepbuffer;

		public int itemflag;
		public dynamic itemtype = new string[7];
		public int t_itemid;
		public int extratext;
		public string itemname;
		public string itemtypename;

		public int equipcon;
		public obj_marker[] h = new obj_marker[3];

		public int checkhp1;
		public int checkhp2;
		public int firstturn;
		public GamemakerObject hb;

		public int norot;
		public bool actual;
		public double thisx;
		public double thisy;
		public int maxradius;
		public double movespeed;
		public int radcon;
		public double xdir;
		public int tcount;

		public GamemakerObject npc;
		public double htimer;
		public double hmax;
		public double spinmax;

		public GamemakerObject doormarker;
		public int rcon;
		public dynamic hathy;
		public int walkcon;

		public int idletimer;
		public double idlefacer;
		public double talkfacer;
		public int talkbuffer;
		public int menu;
		public int submenu;
		public double shopcharx;
		public int[] menuc = new int[20];
		public int[] submenuc = new int[20];
		public int _up_pressed;
		public int _down_pressed;
		public int murder;
		public int moff;
		public string item0pic;
		public string item1pic;
		public string item2pic;
		public string item3pic;
		public int itemtotal;
		public int[] item = new int[7];
		public string[] shopdesc = new string[4];
		public int[] itematk = new int[4];
		public int[] itemdef = new int[4];
		public int[] itemmagic = new int[4];
		public bool[,] canequip = new bool[4, 4];
		public string[] shopitemname = new string[4];
		public int[] buyvalue = new int[4];
		public int sell;
		public int bought;
		public int mainmessage;
		public int minimenuy;
		public int sidemessage;
		public int selling;
		public int glow;
		public int shx;
		public int soldo;
		public int an;
		public int talkanim;
		public string shopkeepsprite;
		public int qualify;
		public int menumax;
		public bool afford;
		public string _legendstring;
		public int sidemessage1;
		public int sidemessage2;
		public int idealmenu;
		public int can;
		public int sellvalue;
		public string roomstring;
		public bool _checked;
		public int teleportmode;
		public string door_destination;
		public string door_location;
		public int on;
		public obj_marker weirdlight;
		public int doortimer;
		public obj_marker dark_marker;
		public int tx;
		public double oy;

		public int traitorp;
		public int tellme;
		public int metotal;
		public double lx;
		public double ly;
		public GamemakerObject puzz1;
		public GamemakerObject puzz2;

		public bool init;
		public bool tracking;
		public bool locked;

		public int leavecon;
		public int boxcon;
		public int boxon;

		public GamemakerObject groundblock;
		public obj_marker ral;
		public GamemakerObject ral2;
		public GamemakerObject sus2;
		public int movecourse;
		public int _event;
		public int movedir;
		public double ix;
		public double iy;
		public bool confirm;
		public int boxcount;
		public int tilecount;
		public GamemakerObject ral3;
		public GamemakerObject sus3;
		public GamemakerObject dl;

		public double rot;
		public double xscale;
		public double yscale;
		public double xcen;
		public double ycen;
		public int dkblue;
		public int dkblue2;
		public int dkblue3;
		public int bgx;
		public int rotcounter;
		public int rotfps;
		public double rotspeed;
		public int check;
		public double bgalpha;
		public double newx1;
		public double newy1;
		public double newx2;
		public double newy2;
		public int trimax;
		public int blackon;
		public double curx;
		public int curl;
		public int curscale;
		public double tempscale;
		public int curw;
		public int ng;

		public int quick;
		public int bulcon;
		public int smax;
		public obj_marker[] sbul = new obj_marker[3];
		public int below;
		public obj_afterimage aft;
		public AudioSource jlaugh;
		public int bultimer;

		public int pirouette;
		public int pirouettecounter;
		public int pfactor;
		public int hypnosis;
		public int hypnosiscounter;
		public int chaosdance;
		public int reminvc;
		public int[] remmaxhp = new int[4];
		public GamemakerObject body;
		public int laughnoise;
		public int beepnoise;
		public int beepbuffer;
		public bool burstnoise;
		public int jturn;
		public int jattack;
		public int condition;
		public double maxdist;
		public double mhpratio;
		public double floatsinerspeed;
		public int dancelv;
		public double flyx;
		public double floatsiner;
		public double offy;

		public int ji;
		public int maxchain;
		public double size;
		public bool debug;
		public int scythecon;
		public int spintimer;
		public int sndcon;
		public double s_xscale;
		public double s_yscale;
		public string s_sprite;
		public double s_y;
		public double s_vspeed;
		public double xsiner;
		public double ysiner;
		public double rotsiner;
		public int dance_side;
		public int dancesiner;
		public int dancemade;
		public double[] shadowx = new double[7];
		public double[] shadowy = new double[7];
		public double[] sfactor = new double[7];
		public double fade_a;
		public double[] dalpha = new double[7];

		public int _ti;

		public double sinadd;
		public double sinx;
		public double siny;
		public double remat;

		public double basex;
		public double idealx;
		public GamemakerObject bomb;
		public double jokerx;
		public double jokery;
		public GamemakerObject jokern;

		public int fire;

		public int whitecon;
		public double whitetimer;
		public double xdiff;
	}
}
