.localvar 0 arguments

:[0]
pushi.e 0
pop.v.i self.dbselect
push.i 16777215
pushi.e -1
pushi.e 0
pop.v.i [array]self.color
push.i 16777215
pushi.e -1
pushi.e 1
pop.v.i [array]self.color
push.i 16777215
pushi.e -1
pushi.e 2
pop.v.i [array]self.color
pushi.e -5
pushi.e 223
push.v [array]global.flag
pushi.e -1
pushi.e 0
pop.v.v [array]self.dcolor
pushi.e -5
pushi.e 224
push.v [array]global.flag
pushi.e -1
pushi.e 1
pop.v.v [array]self.dcolor
pushi.e -5
pushi.e 225
push.v [array]global.flag
pushi.e -1
pushi.e 2
pop.v.v [array]self.dcolor
pushi.e -5
pushi.e 221
push.v [array]global.flag
pushi.e -1
pushi.e 0
pop.v.v [array]self.part
pushi.e -5
pushi.e 220
push.v [array]global.flag
pushi.e -1
pushi.e 1
pop.v.v [array]self.part
pushi.e -5
pushi.e 222
push.v [array]global.flag
pushi.e -1
pushi.e 2
pop.v.v [array]self.part
pushi.e 1
pop.v.i self.a
pushi.e 4
pop.v.i self.s
push.v self.x
pop.v.v self.xx
push.v self.y
pop.v.v self.yy
pushi.e 0
pop.v.i self.siner
pushi.e 0
pop.v.i self.wsiner
pushi.e 1
pop.v.i self.animate
pushi.e 0
pop.v.i self.bad
pushi.e 1
pop.v.i self.value
push.i 16777215
pop.v.i self.basecolor

:[end]