.localvar 0 arguments

:[0]
pushi.e 0
pop.v.i self.bikeflip
pushi.e 0
pop.v.i self.becomeflash
pushi.e 0
pop.v.i self.turnt
pushi.e 0
pop.v.i self.turns
pushi.e 0
pop.v.i self.talktimer
pushi.e 5
pop.v.i self.talkmax
pushi.e 0
pop.v.i self.state
pushi.e 0
pop.v.i self.flash
pushi.e 0
pop.v.i self.siner
pushi.e 0
pop.v.i self.fsiner
pushi.e 0
pop.v.i self.talked
pushi.e 0
pop.v.i self.attacked
pushi.e 0
pop.v.i self.hurt
pushi.e 0
pop.v.i self.hurttimer
pushi.e 0
pop.v.i self.hurtshake
push.i 343249823
pop.v.i self.mywriter
pushi.e 0
pop.v.i self.acting
pushi.e 0
pop.v.i self.actcon
pushi.e 0
pop.v.i self.acttimer
pushi.e 0
pop.v.i self.mercymod
pushi.e 9999
pop.v.i self.maxmercy
pushi.e 0
pop.v.i self.warned
pushi.e 0
pop.v.i self.compliment
pushi.e 0
pop.v.i self.tired
pushi.e 0
pop.v.i self.attacks
pushi.e 0
pop.v.i self.dodgetimer
pushi.e 0
pop.v.i self.candodge
pushi.e 0
pop.v.i self.con
pushi.e 0
pop.v.i self.battlecancel
pushi.e 0
pop.v.i self.nexttry
pushi.e 3
pop.v.i self.mytarget
pushi.e 0
pop.v.i self.image_speed
pushi.e 2
pop.v.i self.image_xscale
pushi.e 2
pop.v.i self.image_yscale
pushi.e 0
pop.v.i self.checked
pushi.e 0
pop.v.i self.crown
pushi.e 0
pop.v.i self.attacktype
pushi.e 0
pop.v.i self.thrown
pushi.e 547
pop.v.i self.thissprite
pushi.e 0
pop.v.i self.scon
pushi.e 0
pop.v.i self.secondtime
pushi.e 0
pop.v.i self.bowcounter
pushi.e 0
pop.v.i self.ralsei_lecture
pushi.e 0
pop.v.i self.milk_counter

:[end]