.localvar 0 arguments

:[0]
pushi.e 0
pop.v.i self.char
pushi.e 0
pop.v.i self.myself
pushi.e 0
pop.v.i self.points
pushi.e 0
pop.v.i self.becomeflash
pushi.e 0
pop.v.i self.state
pushi.e 0
pop.v.i self.flash
pushi.e 0
pop.v.i self.siner
pushi.e 0
pop.v.i self.fsiner
pushi.e 0
pop.v.i self.attacktimer
pushi.e 0
pop.v.i self.attacked
pushi.e 1
pop.v.i self.combatdarken
pushi.e 0
pop.v.i self.darkentimer
pushi.e 0
pop.v.i self.darkify
pushi.e 2
pop.v.i self.image_xscale
pushi.e 2
pop.v.i self.image_yscale
pushi.e 37
pop.v.i self.myheight
pushi.e 34
pop.v.i self.mywidth
pushi.e 0
pop.v.i self.index
pushi.e 0
pop.v.i self.specdraw
pushi.e 0
pop.v.i self.is_auto_susie
pushi.e 829
pop.v.i self.normalsprite
pushi.e 458
pop.v.i self.idlesprite
pushi.e 451
pop.v.i self.actreadysprite
pushi.e 450
pop.v.i self.actsprite
pushi.e 456
pop.v.i self.hurtsprite
pushi.e 449
pop.v.i self.defendsprite
pushi.e 449
pop.v.i self.attackreadysprite
pushi.e 454
pop.v.i self.attacksprite
pushi.e 453
pop.v.i self.itemsprite
pushi.e 452
pop.v.i self.itemreadysprite
pushi.e 498
pop.v.i self.spellreadysprite
pushi.e 497
pop.v.i self.spellsprite
pushi.e 448
pop.v.i self.defeatsprite
pushi.e 447
pop.v.i self.victorysprite
pushi.e 0
pop.v.i self.victoryanim
pushi.e 7
pop.v.i self.actframes
pushi.e 9
pop.v.i self.victoryframes
pushi.e 1
pop.v.i self.defendframes
pushi.e 3
pop.v.i self.itemframes
pushi.e 3
pop.v.i self.attackframes
push.d 0.5
pop.v.d self.attackspeed
pushi.e 7
pop.v.i self.actframes
pushi.e 10
pop.v.i self.actreturnframes
pushi.e 10
pop.v.i self.spellframes
pushi.e 0
pop.v.i self.hurt
pushi.e 0
pop.v.i self.hurttimer
pushi.e 0
pop.v.i self.hurtindex
pushi.e 0
pop.v.i self.acttimer
pushi.e 0
pop.v.i self.defendtimer
pushi.e 0
pop.v.i self.itemed
pushi.e 0
pop.v.i self.tu
push.v self.object_index
pushi.e 202
cmp.i.v EQ
bf [2]

:[1]
pushi.e 829
pop.v.i self.normalsprite
pushi.e 458
pop.v.i self.idlesprite
pushi.e 459
pop.v.i self.defendsprite
pushi.e 456
pop.v.i self.hurtsprite
pushi.e 449
pop.v.i self.attackreadysprite
pushi.e 454
pop.v.i self.attacksprite
pushi.e 453
pop.v.i self.itemsprite
pushi.e 451
pop.v.i self.actreadysprite
pushi.e 450
pop.v.i self.actsprite
pushi.e 452
pop.v.i self.itemreadysprite
pushi.e 451
pop.v.i self.spellreadysprite
pushi.e 450
pop.v.i self.spellsprite
pushi.e 448
pop.v.i self.defeatsprite
pushi.e 447
pop.v.i self.victorysprite
pushi.e 7
pop.v.i self.actframes
pushi.e 10
pop.v.i self.actreturnframes
pushi.e 6
pop.v.i self.attackframes
pushi.e 6
pop.v.i self.itemframes
pushi.e 5
pop.v.i self.defendframes
pushi.e 10
pop.v.i self.spellframes
push.d 0.5
pop.v.d self.attackspeed
push.v self.victorysprite
call.i sprite_get_number(argc=1)
pop.v.v self.victoryframes
pushi.e 68
pop.v.i self.mywidth
pushi.e 74
pop.v.i self.myheight

:[2]
push.v self.object_index
pushi.e 203
cmp.i.v EQ
bf [6]

:[3]
pushi.e 5
pop.v.i self.attackframes
pushi.e 5
pop.v.i self.itemframes
pushi.e 5
pop.v.i self.defendframes
pushi.e 7
pop.v.i self.actframes
pushi.e 10
pop.v.i self.actreturnframes
pushi.e 8
pop.v.i self.spellframes
push.d 0.5
pop.v.d self.attackspeed
pushi.e 183
pop.v.i self.normalsprite
pushi.e 463
pop.v.i self.idlesprite
pushi.e 470
pop.v.i self.defendsprite
pushi.e 469
pop.v.i self.hurtsprite
pushi.e 465
pop.v.i self.actreadysprite
pushi.e 466
pop.v.i self.actsprite
pushi.e 477
pop.v.i self.attackreadysprite
pushi.e 474
pop.v.i self.attacksprite
pushi.e -5
pushi.e 2
push.v [array]global.charweapon
pushi.e 0
cmp.i.v EQ
bf [5]

:[4]
pushi.e 473
pop.v.i self.idlesprite
pushi.e 479
pop.v.i self.attackreadysprite
pushi.e 476
pop.v.i self.attacksprite

:[5]
pushi.e 468
pop.v.i self.itemsprite
pushi.e 467
pop.v.i self.itemreadysprite
pushi.e 462
pop.v.i self.spellreadysprite
pushi.e 464
pop.v.i self.spellsprite
pushi.e 472
pop.v.i self.defeatsprite
pushi.e 461
pop.v.i self.victorysprite
push.v self.victorysprite
call.i sprite_get_number(argc=1)
pop.v.v self.victoryframes
pushi.e 70
pop.v.i self.mywidth
pushi.e 82
pop.v.i self.myheight

:[6]
push.v self.object_index
pushi.e 204
cmp.i.v EQ
bf [end]

:[7]
pushi.e 5
pop.v.i self.attackframes
pushi.e 7
pop.v.i self.itemframes
pushi.e 6
pop.v.i self.defendframes
pushi.e 7
pop.v.i self.actframes
pushi.e 10
pop.v.i self.actreturnframes
push.d 0.5
pop.v.d self.attackspeed
pushi.e 209
pop.v.i self.normalsprite
pushi.e 482
pop.v.i self.idlesprite
pushi.e 494
pop.v.i self.defendsprite
pushi.e 495
pop.v.i self.hurtsprite
pushi.e 490
pop.v.i self.attackreadysprite
pushi.e 491
pop.v.i self.attacksprite
pushi.e 492
pop.v.i self.itemsprite
pushi.e 493
pop.v.i self.itemreadysprite
pushi.e 498
pop.v.i self.spellreadysprite
pushi.e 497
pop.v.i self.spellsprite
pushi.e 487
pop.v.i self.defeatsprite
pushi.e 488
pop.v.i self.victorysprite
pushi.e 485
pop.v.i self.actreadysprite
pushi.e 484
pop.v.i self.actsprite
push.v self.victorysprite
call.i sprite_get_number(argc=1)
pop.v.v self.victoryframes
pushi.e 52
pop.v.i self.mywidth
pushi.e 86
pop.v.i self.myheight

:[end]