.localvar 0 arguments

:[0]
pushi.e 0
pop.v.i self.bikeflip
pushi.e 0
pop.v.i self.becomeflash
pushi.e 0
pop.v.i self.turnt
pushi.e 0
pop.v.i self.turns
pushi.e 0
pop.v.i self.talktimer
pushi.e 60
pop.v.i self.talkmax
pushi.e 0
pop.v.i self.state
pushi.e 0
pop.v.i self.flash
pushi.e 0
pop.v.i self.siner
pushi.e 0
pop.v.i self.fsiner
pushi.e 0
pop.v.i self.talked
pushi.e 0
pop.v.i self.attacked
pushi.e 0
pop.v.i self.hurt
pushi.e 0
pop.v.i self.hurttimer
pushi.e 0
pop.v.i self.hurtshake
push.i 343249823
pop.v.i self.mywriter
pushi.e 0
pop.v.i self.acting
pushi.e 0
pop.v.i self.actcon
pushi.e 0
pop.v.i self.acttimer
pushi.e 0
pop.v.i self.mercymod
pushi.e 9999
pop.v.i self.maxmercy
pushi.e 0
pop.v.i self.warned
pushi.e 0
pop.v.i self.compliment
pushi.e 0
pop.v.i self.tired
pushi.e 0
pop.v.i self.attacks
pushi.e 0
pop.v.i self.dodgetimer
pushi.e 0
pop.v.i self.candodge
pushi.e 0
pop.v.i self.con
pushi.e 0
pop.v.i self.battlecancel
pushi.e 0
pop.v.i self.nexttry
pushi.e 3
pop.v.i self.mytarget
pushi.e 0
pop.v.i self.image_speed
pushi.e 0
pop.v.i self.eyex
pushi.e 0
pop.v.i self.eyey
pushi.e 0
pop.v.i self.eye_angle
pushi.e 0
pop.v.i self.eye_radius
pushi.e 0
pop.v.i self.ponman_eye
pushi.e 2
pop.v.i self.image_xscale
pushi.e 2
pop.v.i self.image_yscale
pushi.e 0
pop.v.i self.image_speed
pushi.e 0
pop.v.i self.siner
pushi.e 0
pop.v.i self.addup
pushi.e 0
pop.v.i self.eyecon
pushi.e 0
pop.v.i self.spinspeed
pushi.e 0
pop.v.i self.shotrefresh
pushi.e 0
pop.v.i self.x_angle
pushi.e 0
pop.v.i self.spintype
pushi.e 0
pop.v.i self.shotbuffer
pushi.e 0
pop.v.i self.grandbuffer
pushi.e 0
pop.v.i self.shotcount
pushi.e 0
pop.v.i self.totalshotcount
pushi.e 1
pop.v.i self.pontotal
pushi.e 0
pop.v.i self.maxtimer
pushi.e 0
pop.v.i self.activetimer
pushi.e 0
pop.v.i self.testtimer
pushi.e 0
pop.v.i self.sleeping
pushi.e 5
pop.v.i self.sleep_index
pushi.e 0
pop.v.i self.becomesleep
pushi.e 0
pop.v.i self.this_index
pushi.e 0
pop.v.i self.lullabied
pushi.e 558
pop.v.i self.idlesprite
pushi.e 558
pop.v.i self.hurtsprite
pushi.e 554
pop.v.i self.sparedsprite

:[end]