.localvar 0 arguments

:[0]
pushi.e 0
pop.v.i self.bikeflip
pushi.e 0
pop.v.i self.becomeflash
pushi.e 0
pop.v.i self.turnt
pushi.e 0
pop.v.i self.turns
pushi.e 0
pop.v.i self.talktimer
pushi.e 90
pop.v.i self.talkmax
pushi.e 0
pop.v.i self.state
pushi.e 0
pop.v.i self.flash
pushi.e 0
pop.v.i self.siner
pushi.e 0
pop.v.i self.fsiner
pushi.e 0
pop.v.i self.talked
pushi.e 0
pop.v.i self.attacked
pushi.e 0
pop.v.i self.hurt
pushi.e 0
pop.v.i self.hurttimer
pushi.e 0
pop.v.i self.hurtshake
push.i 343249823
pop.v.i self.mywriter
pushi.e 0
pop.v.i self.acting
pushi.e 0
pop.v.i self.actcon
pushi.e 0
pop.v.i self.acttimer
pushi.e 0
pop.v.i self.mercymod
pushi.e 9999
pop.v.i self.maxmercy
pushi.e 0
pop.v.i self.warned
pushi.e 0
pop.v.i self.compliment
pushi.e 0
pop.v.i self.attacks
pushi.e 0
pop.v.i self.dodgetimer
pushi.e 0
pop.v.i self.candodge
pushi.e 0
pop.v.i self.con
pushi.e 0
pop.v.i self.plot
pushi.e 0
pop.v.i self.checked
pushi.e 0
pop.v.i self.r_hugtime
pushi.e 0
pop.v.i self.hugtime
pushi.e 0
pop.v.i self.dial
pushi.e 0
pop.v.i self.attackedkris
pushi.e 0
pop.v.i self.hurtkris
pushi.e 0
pop.v.i self.attackcon
pushi.e 0
pop.v.i self.attacktimer
pushi.e 0
pop.v.i self.misstime
pushi.e 0
pop.v.i self.hittime
pushi.e 0
pop.v.i self.defendtime
pushi.e 0
pop.v.i self.won
pushi.e 0
pop.v.i self.hugtime
pushi.e 0
pop.v.i self.hitdum
pushi.e 0
pop.v.i self.ambushed
pushi.e 0
pop.v.i self.battlecancel
pushi.e 0
pop.v.i self.defend_command
pushi.e 0
pop.v.i self.attack_command
pushi.e 0
pop.v.i self.act_command
pushi.e 0
pop.v.i self.spell_command
pushi.e 0
pop.v.i self.spare_command
pushi.e 0
pop.v.i self.spare_used
pushi.e 0
pop.v.i self.item_command
pushi.e 0
pop.v.i self.win_spare
pushi.e 0
pop.v.i self.ral_wrongcommand
pushi.e 0
pop.v.i self.ral_wrongcommand_count
pushi.e 0
pop.v.i self.pacifycon
pushi.e 0
pop.v.i self.sparecon
push.v self.sprite_index
pop.v.v self.sparedsprite
push.v self.sprite_index
pop.v.v self.hurtsprite
push.v self.sprite_index
pop.v.v self.idlesprite
pushi.e -5
pushi.e 1
push.v [array]global.hp
pop.v.v self.kris_inithp
pushi.e 0
pop.v.i self.wontimer

:[end]