.localvar 0 arguments

:[0]
pushi.e 40
pushi.e -5
pushi.e 0
pop.v.i [array]global.input_k
pushi.e 39
pushi.e -5
pushi.e 1
pop.v.i [array]global.input_k
pushi.e 38
pushi.e -5
pushi.e 2
pop.v.i [array]global.input_k
pushi.e 37
pushi.e -5
pushi.e 3
pop.v.i [array]global.input_k
pushi.e 90
pushi.e -5
pushi.e 4
pop.v.i [array]global.input_k
pushi.e 88
pushi.e -5
pushi.e 5
pop.v.i [array]global.input_k
pushi.e 67
pushi.e -5
pushi.e 6
pop.v.i [array]global.input_k
pushi.e 13
pushi.e -5
pushi.e 7
pop.v.i [array]global.input_k
pushi.e 16
pushi.e -5
pushi.e 8
pop.v.i [array]global.input_k
pushi.e 17
pushi.e -5
pushi.e 9
pop.v.i [array]global.input_k
pushi.e 1
pushi.e -5
pushi.e 0
pop.v.i [array]global.input_g
pushi.e 3
pushi.e -5
pushi.e 1
pop.v.i [array]global.input_g
pushi.e 0
pushi.e -5
pushi.e 2
pop.v.i [array]global.input_g
pushi.e 2
pushi.e -5
pushi.e 3
pop.v.i [array]global.input_g
pushi.e 13
pushi.e -5
pushi.e 4
pop.v.i [array]global.input_g
pushi.e 12
pushi.e -5
pushi.e 5
pop.v.i [array]global.input_g
pushi.e 15
pushi.e -5
pushi.e 6
pop.v.i [array]global.input_g
pushi.e 999
pushi.e -5
pushi.e 7
pop.v.i [array]global.input_g
pushi.e 999
pushi.e -5
pushi.e 8
pop.v.i [array]global.input_g
pushi.e 999
pushi.e -5
pushi.e 9
pop.v.i [array]global.input_g

:[end]