.localvar 0 arguments
.localvar 1 len 1077
.localvar 2 i 1078
.localvar 3 objID 1079

:[0]
pushi.e -600
pushi.e -5
pushi.e 0
pop.v.i [array]global.__objectDepths
pushi.e -600
pushi.e -5
pushi.e 1
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 2
pop.v.i [array]global.__objectDepths
pushi.e 10
pushi.e -5
pushi.e 3
pop.v.i [array]global.__objectDepths
pushi.e -5
pushi.e -5
pushi.e 4
pop.v.i [array]global.__objectDepths
pushi.e 2
pushi.e -5
pushi.e 5
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 6
pop.v.i [array]global.__objectDepths
push.i 600000
pushi.e -5
pushi.e 7
pop.v.i [array]global.__objectDepths
push.i 500000
pushi.e -5
pushi.e 8
pop.v.i [array]global.__objectDepths
push.i 900000
pushi.e -5
pushi.e 9
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 10
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 11
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 12
pop.v.i [array]global.__objectDepths
pushi.e -10
pushi.e -5
pushi.e 13
pop.v.i [array]global.__objectDepths
push.i 900000
pushi.e -5
pushi.e 14
pop.v.i [array]global.__objectDepths
pushi.e 2000
pushi.e -5
pushi.e 15
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 16
pop.v.i [array]global.__objectDepths
push.i 100000
pushi.e -5
pushi.e 17
pop.v.i [array]global.__objectDepths
push.i 990000
pushi.e -5
pushi.e 18
pop.v.i [array]global.__objectDepths
push.i 800000
pushi.e -5
pushi.e 19
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 20
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 21
pop.v.i [array]global.__objectDepths
push.i 800000
pushi.e -5
pushi.e 22
pop.v.i [array]global.__objectDepths
push.i 950000
pushi.e -5
pushi.e 23
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 24
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 25
pop.v.i [array]global.__objectDepths
push.i 1100000
pushi.e -5
pushi.e 26
pop.v.i [array]global.__objectDepths
pushi.e 10000
pushi.e -5
pushi.e 27
pop.v.i [array]global.__objectDepths
push.i 100000
pushi.e -5
pushi.e 28
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 29
pop.v.i [array]global.__objectDepths
pushi.e 10000
pushi.e -5
pushi.e 30
pop.v.i [array]global.__objectDepths
push.i 900000
pushi.e -5
pushi.e 31
pop.v.i [array]global.__objectDepths
push.i 800000
pushi.e -5
pushi.e 32
pop.v.i [array]global.__objectDepths
push.i 960000
pushi.e -5
pushi.e 33
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 34
pop.v.i [array]global.__objectDepths
pushi.e 1000
pushi.e -5
pushi.e 35
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 36
pop.v.i [array]global.__objectDepths
pushi.e -1000
pushi.e -5
pushi.e 37
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 38
pop.v.i [array]global.__objectDepths
pushi.e -10
pushi.e -5
pushi.e 39
pop.v.i [array]global.__objectDepths
pushi.e -20
pushi.e -5
pushi.e 40
pop.v.i [array]global.__objectDepths
push.i 50000
pushi.e -5
pushi.e 41
pop.v.i [array]global.__objectDepths
push.i 50000
pushi.e -5
pushi.e 42
pop.v.i [array]global.__objectDepths
push.i 50000
pushi.e -5
pushi.e 43
pop.v.i [array]global.__objectDepths
push.i 50000
pushi.e -5
pushi.e 44
pop.v.i [array]global.__objectDepths
push.i 500000
pushi.e -5
pushi.e 45
pop.v.i [array]global.__objectDepths
push.i 700000
pushi.e -5
pushi.e 46
pop.v.i [array]global.__objectDepths
push.i 700000
pushi.e -5
pushi.e 47
pop.v.i [array]global.__objectDepths
push.i 200000
pushi.e -5
pushi.e 48
pop.v.i [array]global.__objectDepths
pushi.e 100
pushi.e -5
pushi.e 49
pop.v.i [array]global.__objectDepths
push.i 600000
pushi.e -5
pushi.e 50
pop.v.i [array]global.__objectDepths
push.i 900000
pushi.e -5
pushi.e 51
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 52
pop.v.i [array]global.__objectDepths
push.i 500000
pushi.e -5
pushi.e 53
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 54
pop.v.i [array]global.__objectDepths
push.i 800000
pushi.e -5
pushi.e 55
pop.v.i [array]global.__objectDepths
push.i 950000
pushi.e -5
pushi.e 56
pop.v.i [array]global.__objectDepths
push.i 50000
pushi.e -5
pushi.e 57
pop.v.i [array]global.__objectDepths
push.i 50000
pushi.e -5
pushi.e 58
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 59
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 60
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 61
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 62
pop.v.i [array]global.__objectDepths
push.i 900000
pushi.e -5
pushi.e 63
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 64
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 65
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 66
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 67
pop.v.i [array]global.__objectDepths
push.i 100000
pushi.e -5
pushi.e 68
pop.v.i [array]global.__objectDepths
push.i 900000
pushi.e -5
pushi.e 69
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 70
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 71
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 72
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 73
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 74
pop.v.i [array]global.__objectDepths
pushi.e -10
pushi.e -5
pushi.e 75
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 76
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 77
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 78
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 79
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 80
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 81
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 82
pop.v.i [array]global.__objectDepths
pushi.e -10
pushi.e -5
pushi.e 83
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 84
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 85
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 86
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 87
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 88
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 89
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 90
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 91
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 92
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 93
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 94
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 95
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 96
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 97
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 98
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 99
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 100
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 101
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 102
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 103
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 104
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 105
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 106
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 107
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 108
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 109
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 110
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 111
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 112
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 113
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 114
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 115
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 116
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 117
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 118
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 119
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 120
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 121
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 122
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 123
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 124
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 125
pop.v.i [array]global.__objectDepths
push.i 950000
pushi.e -5
pushi.e 126
pop.v.i [array]global.__objectDepths
push.i 1100000
pushi.e -5
pushi.e 127
pop.v.i [array]global.__objectDepths
pushi.e -200
pushi.e -5
pushi.e 128
pop.v.i [array]global.__objectDepths
push.i -40000
pushi.e -5
pushi.e 129
pop.v.i [array]global.__objectDepths
pushi.e -40
pushi.e -5
pushi.e 130
pop.v.i [array]global.__objectDepths
push.i 600000
pushi.e -5
pushi.e 131
pop.v.i [array]global.__objectDepths
pushi.e -20
pushi.e -5
pushi.e 132
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 133
pop.v.i [array]global.__objectDepths
push.i 2000000
pushi.e -5
pushi.e 134
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 135
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 136
pop.v.i [array]global.__objectDepths
push.i -99999
pushi.e -5
pushi.e 137
pop.v.i [array]global.__objectDepths
push.i -99999
pushi.e -5
pushi.e 138
pop.v.i [array]global.__objectDepths
push.i -99999
pushi.e -5
pushi.e 139
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 140
pop.v.i [array]global.__objectDepths
push.i 800000
pushi.e -5
pushi.e 141
pop.v.i [array]global.__objectDepths
push.i 800000
pushi.e -5
pushi.e 142
pop.v.i [array]global.__objectDepths
push.i 500000
pushi.e -5
pushi.e 143
pop.v.i [array]global.__objectDepths
push.i 750000
pushi.e -5
pushi.e 144
pop.v.i [array]global.__objectDepths
push.i 800000
pushi.e -5
pushi.e 145
pop.v.i [array]global.__objectDepths
push.i 990000
pushi.e -5
pushi.e 146
pop.v.i [array]global.__objectDepths
push.i 400000
pushi.e -5
pushi.e 147
pop.v.i [array]global.__objectDepths
pushi.e 10000
pushi.e -5
pushi.e 148
pop.v.i [array]global.__objectDepths
pushi.e 200
pushi.e -5
pushi.e 149
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 150
pop.v.i [array]global.__objectDepths
pushi.e 100
pushi.e -5
pushi.e 151
pop.v.i [array]global.__objectDepths
pushi.e 100
pushi.e -5
pushi.e 152
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 153
pop.v.i [array]global.__objectDepths
pushi.e 100
pushi.e -5
pushi.e 154
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 155
pop.v.i [array]global.__objectDepths
push.i 950000
pushi.e -5
pushi.e 156
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 157
pop.v.i [array]global.__objectDepths
push.i 1100000
pushi.e -5
pushi.e 158
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 159
pop.v.i [array]global.__objectDepths
pushi.e 10
pushi.e -5
pushi.e 160
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 161
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 162
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 163
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 164
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 165
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 166
pop.v.i [array]global.__objectDepths
pushi.e -5
pushi.e -5
pushi.e 167
pop.v.i [array]global.__objectDepths
pushi.e -5
pushi.e -5
pushi.e 168
pop.v.i [array]global.__objectDepths
push.i 950000
pushi.e -5
pushi.e 169
pop.v.i [array]global.__objectDepths
pushi.e 1000
pushi.e -5
pushi.e 170
pop.v.i [array]global.__objectDepths
pushi.e 1000
pushi.e -5
pushi.e 171
pop.v.i [array]global.__objectDepths
push.i 100000
pushi.e -5
pushi.e 172
pop.v.i [array]global.__objectDepths
pushi.e 1000
pushi.e -5
pushi.e 173
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 174
pop.v.i [array]global.__objectDepths
push.i 800000
pushi.e -5
pushi.e 175
pop.v.i [array]global.__objectDepths
push.i 300000
pushi.e -5
pushi.e 176
pop.v.i [array]global.__objectDepths
push.i 300000
pushi.e -5
pushi.e 177
pop.v.i [array]global.__objectDepths
push.i 200000
pushi.e -5
pushi.e 178
pop.v.i [array]global.__objectDepths
pushi.e 10
pushi.e -5
pushi.e 179
pop.v.i [array]global.__objectDepths
pushi.e 10
pushi.e -5
pushi.e 180
pop.v.i [array]global.__objectDepths
push.i 100000
pushi.e -5
pushi.e 181
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 182
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 183
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 184
pop.v.i [array]global.__objectDepths
pushi.e 1
pushi.e -5
pushi.e 185
pop.v.i [array]global.__objectDepths
pushi.e -100
pushi.e -5
pushi.e 186
pop.v.i [array]global.__objectDepths
pushi.e 5
pushi.e -5
pushi.e 187
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 188
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 189
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 190
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 191
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 192
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 193
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 194
pop.v.i [array]global.__objectDepths
pushi.e 200
pushi.e -5
pushi.e 195
pop.v.i [array]global.__objectDepths
pushi.e 2
pushi.e -5
pushi.e 196
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 197
pop.v.i [array]global.__objectDepths
pushi.e -10
pushi.e -5
pushi.e 198
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 199
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 200
pop.v.i [array]global.__objectDepths
pushi.e -20
pushi.e -5
pushi.e 201
pop.v.i [array]global.__objectDepths
pushi.e 100
pushi.e -5
pushi.e 202
pop.v.i [array]global.__objectDepths
pushi.e 100
pushi.e -5
pushi.e 203
pop.v.i [array]global.__objectDepths
pushi.e 100
pushi.e -5
pushi.e 204
pop.v.i [array]global.__objectDepths
pushi.e 100
pushi.e -5
pushi.e 205
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 206
pop.v.i [array]global.__objectDepths
pushi.e 10
pushi.e -5
pushi.e 207
pop.v.i [array]global.__objectDepths
pushi.e 90
pushi.e -5
pushi.e 208
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 209
pop.v.i [array]global.__objectDepths
pushi.e -10
pushi.e -5
pushi.e 210
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 211
pop.v.i [array]global.__objectDepths
pushi.e 1
pushi.e -5
pushi.e 212
pop.v.i [array]global.__objectDepths
pushi.e 3
pushi.e -5
pushi.e 213
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 214
pop.v.i [array]global.__objectDepths
push.i 800000
pushi.e -5
pushi.e 215
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 216
pop.v.i [array]global.__objectDepths
push.i 500000
pushi.e -5
pushi.e 217
pop.v.i [array]global.__objectDepths
push.i 600000
pushi.e -5
pushi.e 218
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 219
pop.v.i [array]global.__objectDepths
push.i 900000
pushi.e -5
pushi.e 220
pop.v.i [array]global.__objectDepths
push.i 900000
pushi.e -5
pushi.e 221
pop.v.i [array]global.__objectDepths
push.i 600000
pushi.e -5
pushi.e 222
pop.v.i [array]global.__objectDepths
push.i 600000
pushi.e -5
pushi.e 223
pop.v.i [array]global.__objectDepths
push.i 800000
pushi.e -5
pushi.e 224
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 225
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 226
pop.v.i [array]global.__objectDepths
pushi.e -20
pushi.e -5
pushi.e 227
pop.v.i [array]global.__objectDepths
pushi.e -10
pushi.e -5
pushi.e 228
pop.v.i [array]global.__objectDepths
pushi.e -20
pushi.e -5
pushi.e 229
pop.v.i [array]global.__objectDepths
pushi.e -1
pushi.e -5
pushi.e 230
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 231
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 232
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 233
pop.v.i [array]global.__objectDepths
pushi.e 90
pushi.e -5
pushi.e 234
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 235
pop.v.i [array]global.__objectDepths
pushi.e 90
pushi.e -5
pushi.e 236
pop.v.i [array]global.__objectDepths
pushi.e 90
pushi.e -5
pushi.e 237
pop.v.i [array]global.__objectDepths
pushi.e 90
pushi.e -5
pushi.e 238
pop.v.i [array]global.__objectDepths
pushi.e 10
pushi.e -5
pushi.e 239
pop.v.i [array]global.__objectDepths
pushi.e 6
pushi.e -5
pushi.e 240
pop.v.i [array]global.__objectDepths
pushi.e 15
pushi.e -5
pushi.e 241
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 242
pop.v.i [array]global.__objectDepths
pushi.e 10
pushi.e -5
pushi.e 243
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 244
pop.v.i [array]global.__objectDepths
pushi.e 4
pushi.e -5
pushi.e 245
pop.v.i [array]global.__objectDepths
pushi.e 5
pushi.e -5
pushi.e 246
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 247
pop.v.i [array]global.__objectDepths
pushi.e 10
pushi.e -5
pushi.e 248
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 249
pop.v.i [array]global.__objectDepths
pushi.e 90
pushi.e -5
pushi.e 250
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 251
pop.v.i [array]global.__objectDepths
pushi.e 90
pushi.e -5
pushi.e 252
pop.v.i [array]global.__objectDepths
pushi.e 90
pushi.e -5
pushi.e 253
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 254
pop.v.i [array]global.__objectDepths
pushi.e 1
pushi.e -5
pushi.e 255
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 256
pop.v.i [array]global.__objectDepths
pushi.e 4
pushi.e -5
pushi.e 257
pop.v.i [array]global.__objectDepths
pushi.e 1
pushi.e -5
pushi.e 258
pop.v.i [array]global.__objectDepths
push.i 100000
pushi.e -5
pushi.e 259
pop.v.i [array]global.__objectDepths
pushi.e 90
pushi.e -5
pushi.e 260
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 261
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 262
pop.v.i [array]global.__objectDepths
pushi.e 15
pushi.e -5
pushi.e 263
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 264
pop.v.i [array]global.__objectDepths
pushi.e -5
pushi.e -5
pushi.e 265
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 266
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 267
pop.v.i [array]global.__objectDepths
pushi.e 5
pushi.e -5
pushi.e 268
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 269
pop.v.i [array]global.__objectDepths
push.i 800000
pushi.e -5
pushi.e 270
pop.v.i [array]global.__objectDepths
pushi.e 50
pushi.e -5
pushi.e 271
pop.v.i [array]global.__objectDepths
pushi.e -20
pushi.e -5
pushi.e 272
pop.v.i [array]global.__objectDepths
pushi.e 90
pushi.e -5
pushi.e 273
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 274
pop.v.i [array]global.__objectDepths
pushi.e 90
pushi.e -5
pushi.e 275
pop.v.i [array]global.__objectDepths
pushi.e -20
pushi.e -5
pushi.e 276
pop.v.i [array]global.__objectDepths
pushi.e 2
pushi.e -5
pushi.e 277
pop.v.i [array]global.__objectDepths
pushi.e 90
pushi.e -5
pushi.e 278
pop.v.i [array]global.__objectDepths
pushi.e 90
pushi.e -5
pushi.e 279
pop.v.i [array]global.__objectDepths
pushi.e 90
pushi.e -5
pushi.e 280
pop.v.i [array]global.__objectDepths
pushi.e 95
pushi.e -5
pushi.e 281
pop.v.i [array]global.__objectDepths
pushi.e 90
pushi.e -5
pushi.e 282
pop.v.i [array]global.__objectDepths
pushi.e 90
pushi.e -5
pushi.e 283
pop.v.i [array]global.__objectDepths
pushi.e 10
pushi.e -5
pushi.e 284
pop.v.i [array]global.__objectDepths
pushi.e 90
pushi.e -5
pushi.e 285
pop.v.i [array]global.__objectDepths
pushi.e 90
pushi.e -5
pushi.e 286
pop.v.i [array]global.__objectDepths
pushi.e 90
pushi.e -5
pushi.e 287
pop.v.i [array]global.__objectDepths
pushi.e 90
pushi.e -5
pushi.e 288
pop.v.i [array]global.__objectDepths
pushi.e 90
pushi.e -5
pushi.e 289
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 290
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 291
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 292
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 293
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 294
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 295
pop.v.i [array]global.__objectDepths
pushi.e -10
pushi.e -5
pushi.e 296
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 297
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 298
pop.v.i [array]global.__objectDepths
pushi.e 10000
pushi.e -5
pushi.e 299
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 300
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 301
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 302
pop.v.i [array]global.__objectDepths
pushi.e 5
pushi.e -5
pushi.e 303
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 304
pop.v.i [array]global.__objectDepths
pushi.e 1
pushi.e -5
pushi.e 305
pop.v.i [array]global.__objectDepths
pushi.e 50
pushi.e -5
pushi.e 306
pop.v.i [array]global.__objectDepths
pushi.e 50
pushi.e -5
pushi.e 307
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 308
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 309
pop.v.i [array]global.__objectDepths
pushi.e 10
pushi.e -5
pushi.e 310
pop.v.i [array]global.__objectDepths
pushi.e 10
pushi.e -5
pushi.e 311
pop.v.i [array]global.__objectDepths
pushi.e 1
pushi.e -5
pushi.e 312
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 313
pop.v.i [array]global.__objectDepths
pushi.e 4
pushi.e -5
pushi.e 314
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 315
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 316
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 317
pop.v.i [array]global.__objectDepths
pushi.e 1000
pushi.e -5
pushi.e 318
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 319
pop.v.i [array]global.__objectDepths
pushi.e -9999
pushi.e -5
pushi.e 320
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 321
pop.v.i [array]global.__objectDepths
pushi.e 50
pushi.e -5
pushi.e 322
pop.v.i [array]global.__objectDepths
pushi.e -100
pushi.e -5
pushi.e 323
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 324
pop.v.i [array]global.__objectDepths
pushi.e 10
pushi.e -5
pushi.e 325
pop.v.i [array]global.__objectDepths
pushi.e -20
pushi.e -5
pushi.e 326
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 327
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 328
pop.v.i [array]global.__objectDepths
push.i 60000
pushi.e -5
pushi.e 329
pop.v.i [array]global.__objectDepths
push.i 60000
pushi.e -5
pushi.e 330
pop.v.i [array]global.__objectDepths
pushi.e 100
pushi.e -5
pushi.e 331
pop.v.i [array]global.__objectDepths
push.i 60000
pushi.e -5
pushi.e 332
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 333
pop.v.i [array]global.__objectDepths
pushi.e 100
pushi.e -5
pushi.e 334
pop.v.i [array]global.__objectDepths
pushi.e 100
pushi.e -5
pushi.e 335
pop.v.i [array]global.__objectDepths
pushi.e 100
pushi.e -5
pushi.e 336
pop.v.i [array]global.__objectDepths
pushi.e 100
pushi.e -5
pushi.e 337
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 338
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 339
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 340
pop.v.i [array]global.__objectDepths
push.s "obj_choicer_old"@2997
pushi.e -5
pushi.e 0
pop.v.s [array]global.__objectNames
push.s "obj_choicer_neo"@2999
pushi.e -5
pushi.e 1
pop.v.s [array]global.__objectNames
push.s "obj_face"@3000
pushi.e -5
pushi.e 2
pop.v.s [array]global.__objectNames
push.s "obj_face_parent"@3001
pushi.e -5
pushi.e 3
pop.v.s [array]global.__objectNames
push.s "obj_smallface"@3002
pushi.e -5
pushi.e 4
pop.v.s [array]global.__objectNames
push.s "obj_dialoguer"@3003
pushi.e -5
pushi.e 5
pop.v.s [array]global.__objectNames
push.s "obj_writer"@3004
pushi.e -5
pushi.e 6
pop.v.s [array]global.__objectNames
push.s "obj_fallpaper"@3005
pushi.e -5
pushi.e 7
pop.v.s [array]global.__objectNames
push.s "obj_insideclosetcutscene"@3006
pushi.e -5
pushi.e 8
pop.v.s [array]global.__objectNames
push.s "obj_darkdoor"@3007
pushi.e -5
pushi.e 9
pop.v.s [array]global.__objectNames
push.s "obj_classscene"@3008
pushi.e -5
pushi.e 10
pop.v.s [array]global.__objectNames
push.s "obj_schoollobbycutscene"@3009
pushi.e -5
pushi.e 11
pop.v.s [array]global.__objectNames
push.s "obj_schooldesk"@3010
pushi.e -5
pushi.e 12
pop.v.s [array]global.__objectNames
push.s "obj_tem_school"@3011
pushi.e -5
pushi.e 13
pop.v.s [array]global.__objectNames
push.s "obj_torielclass_event"@3012
pushi.e -5
pushi.e 14
pop.v.s [array]global.__objectNames
push.s "obj_unusedclassevent"@3013
pushi.e -5
pushi.e 15
pop.v.s [array]global.__objectNames
push.s "obj_alphysdesk"@3014
pushi.e -5
pushi.e 16
pop.v.s [array]global.__objectNames
push.s "obj_rudy"@3015
pushi.e -5
pushi.e 17
pop.v.s [array]global.__objectNames
push.s "obj_church_event"@3016
pushi.e -5
pushi.e 18
pop.v.s [array]global.__objectNames
push.s "obj_town_shelter_event"@3017
pushi.e -5
pushi.e 19
pop.v.s [array]global.__objectNames
push.s "obj_town_event"@3018
pushi.e -5
pushi.e 20
pop.v.s [array]global.__objectNames
push.s "obj_alphysalley_event"@3019
pushi.e -5
pushi.e 21
pop.v.s [array]global.__objectNames
push.s "obj_flowershop_event"@3020
pushi.e -5
pushi.e 22
pop.v.s [array]global.__objectNames
push.s "obj_onionbody"@3021
pushi.e -5
pushi.e 23
pop.v.s [array]global.__objectNames
push.s "obj_onion_event"@3022
pushi.e -5
pushi.e 24
pop.v.s [array]global.__objectNames
push.s "obj_carcutscene"@3023
pushi.e -5
pushi.e 25
pop.v.s [array]global.__objectNames
push.s "obj_hallway_mirror"@3024
pushi.e -5
pushi.e 26
pop.v.s [array]global.__objectNames
push.s "obj_krisroom"@3025
pushi.e -5
pushi.e 27
pop.v.s [array]global.__objectNames
push.s "obj_rurus_checker_event"@3026
pushi.e -5
pushi.e 28
pop.v.s [array]global.__objectNames
push.s "obj_cc_event"@3027
pushi.e -5
pushi.e 29
pop.v.s [array]global.__objectNames
push.s "obj_jokerbattleevent"@3028
pushi.e -5
pushi.e 30
pop.v.s [array]global.__objectNames
push.s "obj_elevatorcontroller"@3029
pushi.e -5
pushi.e 31
pop.v.s [array]global.__objectNames
push.s "obj_lancerbakesale_event"@3030
pushi.e -5
pushi.e 32
pop.v.s [array]global.__objectNames
push.s "obj_cloverpuzzle_event"@3031
pushi.e -5
pushi.e 33
pop.v.s [array]global.__objectNames
push.s "obj_prisonevent"@3032
pushi.e -5
pushi.e 34
pop.v.s [array]global.__objectNames
push.s "obj_lancerbattle2_event"@3033
pushi.e -5
pushi.e 35
pop.v.s [array]global.__objectNames
push.s "obj_lancerchase2"@3034
pushi.e -5
pushi.e 36
pop.v.s [array]global.__objectNames
push.s "obj_castlefront_event"@3035
pushi.e -5
pushi.e 37
pop.v.s [array]global.__objectNames
push.s "obj_susieandlancer_event"@3036
pushi.e -5
pushi.e 38
pop.v.s [array]global.__objectNames
push.s "obj_thrashcontroller"@3037
pushi.e -5
pushi.e 39
pop.v.s [array]global.__objectNames
push.s "obj_thrashmachine"@3038
pushi.e -5
pushi.e 40
pop.v.s [array]global.__objectNames
push.s "obj_thrashmaker_event"@3039
pushi.e -5
pushi.e 41
pop.v.s [array]global.__objectNames
push.s "obj_suitspuzzle_event"@3040
pushi.e -5
pushi.e 42
pop.v.s [array]global.__objectNames
push.s "obj_susiebadguy_event"@3041
pushi.e -5
pushi.e 43
pop.v.s [array]global.__objectNames
push.s "obj_thrashafter_event"@3042
pushi.e -5
pushi.e 44
pop.v.s [array]global.__objectNames
push.s "obj_thrashafter_follow"@3043
pushi.e -5
pushi.e 45
pop.v.s [array]global.__objectNames
push.s "obj_rurus_appear"@3044
pushi.e -5
pushi.e 46
pop.v.s [array]global.__objectNames
push.s "obj_rurus_event"@3045
pushi.e -5
pushi.e 47
pop.v.s [array]global.__objectNames
push.s "obj_lancerscare2"@3046
pushi.e -5
pushi.e 48
pop.v.s [array]global.__objectNames
push.s "obj_scarelancerevent"@3047
pushi.e -5
pushi.e 49
pop.v.s [array]global.__objectNames
push.s "obj_getsusieevent"@3048
pushi.e -5
pushi.e 50
pop.v.s [array]global.__objectNames
push.s "obj_boxpuzzle_event"@3049
pushi.e -5
pushi.e 51
pop.v.s [array]global.__objectNames
push.s "obj_hathyfightevent"@3050
pushi.e -5
pushi.e 52
pop.v.s [array]global.__objectNames
push.s "obj_darkdoorevent"@3051
pushi.e -5
pushi.e 53
pop.v.s [array]global.__objectNames
push.s "obj_tutorialbattleevent"@3052
pushi.e -5
pushi.e 54
pop.v.s [array]global.__objectNames
push.s "obj_ralsei_runevent"@3053
pushi.e -5
pushi.e 55
pop.v.s [array]global.__objectNames
push.s "obj_lancerguide"@3054
pushi.e -5
pushi.e 56
pop.v.s [array]global.__objectNames
push.s "obj_thrashzone_event"@3055
pushi.e -5
pushi.e 57
pop.v.s [array]global.__objectNames
push.s "obj_insultzone_event"@3056
pushi.e -5
pushi.e 58
pop.v.s [array]global.__objectNames
push.s "obj_preforest_event"@3057
pushi.e -5
pushi.e 59
pop.v.s [array]global.__objectNames
push.s "obj_candytree_event"@3058
pushi.e -5
pushi.e 60
pop.v.s [array]global.__objectNames
push.s "obj_cloverhole"@3059
pushi.e -5
pushi.e 61
pop.v.s [array]global.__objectNames
push.s "obj_npc_hammerguy"@3060
pushi.e -5
pushi.e 62
pop.v.s [array]global.__objectNames
push.s "obj_shortcut_door"@3061
pushi.e -5
pushi.e 63
pop.v.s [array]global.__objectNames
push.s "obj_npc_puzzlemaster1"@3062
pushi.e -5
pushi.e 64
pop.v.s [array]global.__objectNames
push.s "obj_npc_puzzlemaster2"@3063
pushi.e -5
pushi.e 65
pop.v.s [array]global.__objectNames
push.s "obj_cakesmoke"@3064
pushi.e -5
pushi.e 66
pop.v.s [array]global.__objectNames
push.s "obj_npc_susiedark"@3065
pushi.e -5
pushi.e 67
pop.v.s [array]global.__objectNames
push.s "obj_darkcastle_event"@3066
pushi.e -5
pushi.e 68
pop.v.s [array]global.__objectNames
push.s "obj_darklanding"@3067
pushi.e -5
pushi.e 69
pop.v.s [array]global.__objectNames
push.s "obj_wobblything_slide"@3068
pushi.e -5
pushi.e 70
pop.v.s [array]global.__objectNames
push.s "obj_lancerslideevent"@3069
pushi.e -5
pushi.e 71
pop.v.s [array]global.__objectNames
push.s "obj_lancerchaseevent"@3070
pushi.e -5
pushi.e 72
pop.v.s [array]global.__objectNames
push.s "obj_darkslide"@3071
pushi.e -5
pushi.e 73
pop.v.s [array]global.__objectNames
push.s "obj_darkwakeevent"@3072
pushi.e -5
pushi.e 74
pop.v.s [array]global.__objectNames
push.s "obj_savepoint"@3073
pushi.e -5
pushi.e 75
pop.v.s [array]global.__objectNames
push.s "obj_readable"@3074
pushi.e -5
pushi.e 76
pop.v.s [array]global.__objectNames
push.s "obj_animation"@3075
pushi.e -5
pushi.e 77
pop.v.s [array]global.__objectNames
push.s "obj_marker"@3076
pushi.e -5
pushi.e 78
pop.v.s [array]global.__objectNames
push.s "obj_marker2"@3077
pushi.e -5
pushi.e 79
pop.v.s [array]global.__objectNames
push.s "obj_readable_room1"@3078
pushi.e -5
pushi.e 80
pop.v.s [array]global.__objectNames
push.s "obj_interactablesolid"@3079
pushi.e -5
pushi.e 81
pop.v.s [array]global.__objectNames
push.s "obj_npc_toriel"@3080
pushi.e -5
pushi.e 82
pop.v.s [array]global.__objectNames
push.s "obj_npc_facing"@3081
pushi.e -5
pushi.e 83
pop.v.s [array]global.__objectNames
push.s "obj_npc_room"@3082
pushi.e -5
pushi.e 84
pop.v.s [array]global.__objectNames
push.s "obj_npc_room_animated"@3083
pushi.e -5
pushi.e 85
pop.v.s [array]global.__objectNames
push.s "obj_treasure_room"@3084
pushi.e -5
pushi.e 86
pop.v.s [array]global.__objectNames
push.s "obj_npc_sign"@3085
pushi.e -5
pushi.e 87
pop.v.s [array]global.__objectNames
push.s "obj_event_room"@3086
pushi.e -5
pushi.e 88
pop.v.s [array]global.__objectNames
push.s "obj_interactable"@3087
pushi.e -5
pushi.e 89
pop.v.s [array]global.__objectNames
push.s "obj_doorA"@3088
pushi.e -5
pushi.e 90
pop.v.s [array]global.__objectNames
push.s "obj_doorA_musfade"@3089
pushi.e -5
pushi.e 91
pop.v.s [array]global.__objectNames
push.s "obj_doorB_musfade"@3090
pushi.e -5
pushi.e 92
pop.v.s [array]global.__objectNames
push.s "obj_doorB"@3091
pushi.e -5
pushi.e 93
pop.v.s [array]global.__objectNames
push.s "obj_doorC"@3092
pushi.e -5
pushi.e 94
pop.v.s [array]global.__objectNames
push.s "obj_doorC_musfade"@3093
pushi.e -5
pushi.e 95
pop.v.s [array]global.__objectNames
push.s "obj_doorD"@3094
pushi.e -5
pushi.e 96
pop.v.s [array]global.__objectNames
push.s "obj_doorD_musfade"@3095
pushi.e -5
pushi.e 97
pop.v.s [array]global.__objectNames
push.s "obj_doorE"@3096
pushi.e -5
pushi.e 98
pop.v.s [array]global.__objectNames
push.s "obj_doorF"@3097
pushi.e -5
pushi.e 99
pop.v.s [array]global.__objectNames
push.s "obj_doorX"@3098
pushi.e -5
pushi.e 100
pop.v.s [array]global.__objectNames
push.s "obj_doorX_musfade"@3099
pushi.e -5
pushi.e 101
pop.v.s [array]global.__objectNames
push.s "obj_doorw_musfade"@3100
pushi.e -5
pushi.e 102
pop.v.s [array]global.__objectNames
push.s "obj_doorparent"@3101
pushi.e -5
pushi.e 103
pop.v.s [array]global.__objectNames
push.s "obj_markerA"@3102
pushi.e -5
pushi.e 104
pop.v.s [array]global.__objectNames
push.s "obj_markerB"@3103
pushi.e -5
pushi.e 105
pop.v.s [array]global.__objectNames
push.s "obj_markerC"@3104
pushi.e -5
pushi.e 106
pop.v.s [array]global.__objectNames
push.s "obj_markerD"@3105
pushi.e -5
pushi.e 107
pop.v.s [array]global.__objectNames
push.s "obj_markerE"@3106
pushi.e -5
pushi.e 108
pop.v.s [array]global.__objectNames
push.s "obj_markerF"@3107
pushi.e -5
pushi.e 109
pop.v.s [array]global.__objectNames
push.s "obj_markerr"@3108
pushi.e -5
pushi.e 110
pop.v.s [array]global.__objectNames
push.s "obj_markers"@3109
pushi.e -5
pushi.e 111
pop.v.s [array]global.__objectNames
push.s "obj_markert"@3110
pushi.e -5
pushi.e 112
pop.v.s [array]global.__objectNames
push.s "obj_markeru"@3111
pushi.e -5
pushi.e 113
pop.v.s [array]global.__objectNames
push.s "obj_markerv"@3112
pushi.e -5
pushi.e 114
pop.v.s [array]global.__objectNames
push.s "obj_markerw"@3113
pushi.e -5
pushi.e 115
pop.v.s [array]global.__objectNames
push.s "obj_markerX"@3114
pushi.e -5
pushi.e 116
pop.v.s [array]global.__objectNames
push.s "obj_doorW"@3115
pushi.e -5
pushi.e 117
pop.v.s [array]global.__objectNames
push.s "obj_musicer"@3116
pushi.e -5
pushi.e 118
pop.v.s [array]global.__objectNames
push.s "obj_musicer_darkcliff"@3117
pushi.e -5
pushi.e 119
pop.v.s [array]global.__objectNames
push.s "obj_musicer_town"@3118
pushi.e -5
pushi.e 120
pop.v.s [array]global.__objectNames
push.s "obj_musicer_field"@3119
pushi.e -5
pushi.e 121
pop.v.s [array]global.__objectNames
push.s "obj_musicer_forest"@3120
pushi.e -5
pushi.e 122
pop.v.s [array]global.__objectNames
push.s "obj_musicer_quietforest"@3121
pushi.e -5
pushi.e 123
pop.v.s [array]global.__objectNames
push.s "obj_musicer_man"@3122
pushi.e -5
pushi.e 124
pop.v.s [array]global.__objectNames
push.s "obj_musicer_darkcastle"@3123
pushi.e -5
pushi.e 125
pop.v.s [array]global.__objectNames
push.s "obj_musicer_bird"@3124
pushi.e -5
pushi.e 126
pop.v.s [array]global.__objectNames
push.s "obj_wave_fx"@3125
pushi.e -5
pushi.e 127
pop.v.s [array]global.__objectNames
push.s "obj_astream"@3126
pushi.e -5
pushi.e 128
pop.v.s [array]global.__objectNames
push.s "obj_gameover_init"@3127
pushi.e -5
pushi.e 129
pop.v.s [array]global.__objectNames
push.s "obj_ralseibook"@3128
pushi.e -5
pushi.e 130
pop.v.s [array]global.__objectNames
push.s "obj_jokerbg_triangle_real"@3129
pushi.e -5
pushi.e 131
pop.v.s [array]global.__objectNames
push.s "obj_fieldmuslogo"@3130
pushi.e -5
pushi.e 132
pop.v.s [array]global.__objectNames
push.s "obj_backgrounder_standard"@3131
pushi.e -5
pushi.e 133
pop.v.s [array]global.__objectNames
push.s "obj_backgrounder_sprite"@3132
pushi.e -5
pushi.e 134
pop.v.s [array]global.__objectNames
push.s "obj_backgrounderparent"@3133
pushi.e -5
pushi.e 135
pop.v.s [array]global.__objectNames
push.s "obj_panner"@3134
pushi.e -5
pushi.e 136
pop.v.s [array]global.__objectNames
push.s "obj_fadeout"@3135
pushi.e -5
pushi.e 137
pop.v.s [array]global.__objectNames
push.s "obj_fadein"@3136
pushi.e -5
pushi.e 138
pop.v.s [array]global.__objectNames
push.s "obj_persistentfadein"@3137
pushi.e -5
pushi.e 139
pop.v.s [array]global.__objectNames
push.s "obj_shake"@3138
pushi.e -5
pushi.e 140
pop.v.s [array]global.__objectNames
push.s "obj_castle_torch"@3139
pushi.e -5
pushi.e 141
pop.v.s [array]global.__objectNames
push.s "obj_castle_house"@3140
pushi.e -5
pushi.e 142
pop.v.s [array]global.__objectNames
push.s "obj_bluhpainting"@3141
pushi.e -5
pushi.e 143
pop.v.s [array]global.__objectNames
push.s "obj_lightfairy"@3142
pushi.e -5
pushi.e 144
pop.v.s [array]global.__objectNames
push.s "obj_blocktree_bg"@3143
pushi.e -5
pushi.e 145
pop.v.s [array]global.__objectNames
push.s "obj_purplegrass"@3144
pushi.e -5
pushi.e 146
pop.v.s [array]global.__objectNames
push.s "obj_slidedust"@3145
pushi.e -5
pushi.e 147
pop.v.s [array]global.__objectNames
push.s "obj_darklancer"@3146
pushi.e -5
pushi.e 148
pop.v.s [array]global.__objectNames
push.s "obj_dustball"@3147
pushi.e -5
pushi.e 149
pop.v.s [array]global.__objectNames
push.s "obj_dustball_pilebreak"@3148
pushi.e -5
pushi.e 150
pop.v.s [array]global.__objectNames
push.s "obj_dustpile"@3149
pushi.e -5
pushi.e 151
pop.v.s [array]global.__objectNames
push.s "obj_dustpile_susie"@3150
pushi.e -5
pushi.e 152
pop.v.s [array]global.__objectNames
push.s "obj_wobblything"@3151
pushi.e -5
pushi.e 153
pop.v.s [array]global.__objectNames
push.s "obj_wobblything_evil"@3152
pushi.e -5
pushi.e 154
pop.v.s [array]global.__objectNames
push.s "obj_anim"@3153
pushi.e -5
pushi.e 155
pop.v.s [array]global.__objectNames
push.s "obj_kingcutscene"@3154
pushi.e -5
pushi.e 156
pop.v.s [array]global.__objectNames
push.s "obj_shakeobj"@3155
pushi.e -5
pushi.e 157
pop.v.s [array]global.__objectNames
push.s "obj_darkfountain"@3156
pushi.e -5
pushi.e 158
pop.v.s [array]global.__objectNames
push.s "obj_darkfountain_event"@3157
pushi.e -5
pushi.e 159
pop.v.s [array]global.__objectNames
push.s "obj_fountainkris"@3158
pushi.e -5
pushi.e 160
pop.v.s [array]global.__objectNames
push.s "obj_chaseenemy"@3159
pushi.e -5
pushi.e 161
pop.v.s [array]global.__objectNames
push.s "obj_excblcon"@3160
pushi.e -5
pushi.e 162
pop.v.s [array]global.__objectNames
push.s "obj_testoverworldenemy"@3161
pushi.e -5
pushi.e 163
pop.v.s [array]global.__objectNames
push.s "obj_encounterbasic"@3162
pushi.e -5
pushi.e 164
pop.v.s [array]global.__objectNames
push.s "obj_caterpillarchara"@3163
pushi.e -5
pushi.e 165
pop.v.s [array]global.__objectNames
push.s "obj_darkcontroller"@3164
pushi.e -5
pushi.e 166
pop.v.s [array]global.__objectNames
push.s "obj_healwriter"@3165
pushi.e -5
pushi.e 167
pop.v.s [array]global.__objectNames
push.s "obj_menuwriter"@3166
pushi.e -5
pushi.e 168
pop.v.s [array]global.__objectNames
push.s "obj_battlealphaer"@3167
pushi.e -5
pushi.e 169
pop.v.s [array]global.__objectNames
push.s "obj_starwalker_battle"@3168
pushi.e -5
pushi.e 170
pop.v.s [array]global.__objectNames
push.s "obj_starwalker_overworld"@3169
pushi.e -5
pushi.e 171
pop.v.s [array]global.__objectNames
push.s "obj_starwalker_offswitch"@3170
pushi.e -5
pushi.e 172
pop.v.s [array]global.__objectNames
push.s "obj_overworldheart"@3171
pushi.e -5
pushi.e 173
pop.v.s [array]global.__objectNames
push.s "obj_scissordancer"@3172
pushi.e -5
pushi.e 174
pop.v.s [array]global.__objectNames
push.s "obj_dancer_gen"@3173
pushi.e -5
pushi.e 175
pop.v.s [array]global.__objectNames
push.s "obj_darkponman_ow"@3174
pushi.e -5
pushi.e 176
pop.v.s [array]global.__objectNames
push.s "obj_ob_gen"@3175
pushi.e -5
pushi.e 177
pop.v.s [array]global.__objectNames
push.s "obj_ob_checkertile"@3176
pushi.e -5
pushi.e 178
pop.v.s [array]global.__objectNames
push.s "obj_overworld_spade_homing"@3177
pushi.e -5
pushi.e 179
pop.v.s [array]global.__objectNames
push.s "obj_overworld_spade"@3178
pushi.e -5
pushi.e 180
pop.v.s [array]global.__objectNames
push.s "obj_overworld_spademaker"@3179
pushi.e -5
pushi.e 181
pop.v.s [array]global.__objectNames
push.s "obj_overworldbulletparent"@3180
pushi.e -5
pushi.e 182
pop.v.s [array]global.__objectNames
push.s "obj_afterimage"@3181
pushi.e -5
pushi.e 183
pop.v.s [array]global.__objectNames
push.s "obj_afterimage_grow"@3182
pushi.e -5
pushi.e 184
pop.v.s [array]global.__objectNames
push.s "obj_attackpress"@3183
pushi.e -5
pushi.e 185
pop.v.s [array]global.__objectNames
push.s "obj_basicattack"@3184
pushi.e -5
pushi.e 186
pop.v.s [array]global.__objectNames
push.s "obj_battlecontroller"@3185
pushi.e -5
pushi.e 187
pop.v.s [array]global.__objectNames
push.s "obj_battlesolid"@3186
pushi.e -5
pushi.e 188
pop.v.s [array]global.__objectNames
push.s "obj_bulletgenparent"@3187
pushi.e -5
pushi.e 189
pop.v.s [array]global.__objectNames
push.s "obj_bulletparent"@3188
pushi.e -5
pushi.e 190
pop.v.s [array]global.__objectNames
push.s "obj_burstbolt"@3189
pushi.e -5
pushi.e 191
pop.v.s [array]global.__objectNames
push.s "obj_chasebullet"@3190
pushi.e -5
pushi.e 192
pop.v.s [array]global.__objectNames
push.s "obj_collidebullet"@3191
pushi.e -5
pushi.e 193
pop.v.s [array]global.__objectNames
push.s "obj_regularbullet_permanent"@3192
pushi.e -5
pushi.e 194
pop.v.s [array]global.__objectNames
push.s "obj_darkener"@3193
pushi.e -5
pushi.e 195
pop.v.s [array]global.__objectNames
push.s "obj_grazebox"@3194
pushi.e -5
pushi.e 196
pop.v.s [array]global.__objectNames
push.s "obj_healeffect"@3195
pushi.e -5
pushi.e 197
pop.v.s [array]global.__objectNames
push.s "obj_healsparkle"@3196
pushi.e -5
pushi.e 198
pop.v.s [array]global.__objectNames
push.s "obj_heartburst"@3197
pushi.e -5
pushi.e 199
pop.v.s [array]global.__objectNames
push.s "obj_heartmarker"@3198
pushi.e -5
pushi.e 200
pop.v.s [array]global.__objectNames
push.s "obj_lancerbike"@3199
pushi.e -5
pushi.e 201
pop.v.s [array]global.__objectNames
push.s "obj_herokris"@3200
pushi.e -5
pushi.e 202
pop.v.s [array]global.__objectNames
push.s "obj_herosusie"@3201
pushi.e -5
pushi.e 203
pop.v.s [array]global.__objectNames
push.s "obj_heroralsei"@3202
pushi.e -5
pushi.e 204
pop.v.s [array]global.__objectNames
push.s "obj_heroparent"@3203
pushi.e -5
pushi.e 205
pop.v.s [array]global.__objectNames
push.s "obj_initializer"@3204
pushi.e -5
pushi.e 206
pop.v.s [array]global.__objectNames
push.s "obj_krisplace"@3205
pushi.e -5
pushi.e 207
pop.v.s [array]global.__objectNames
push.s "obj_monster1"@3206
pushi.e -5
pushi.e 208
pop.v.s [array]global.__objectNames
push.s "obj_moveheart"@3207
pushi.e -5
pushi.e 209
pop.v.s [array]global.__objectNames
push.s "obj_regularbullet"@3208
pushi.e -5
pushi.e 210
pop.v.s [array]global.__objectNames
push.s "obj_returnheart"@3209
pushi.e -5
pushi.e 211
pop.v.s [array]global.__objectNames
push.s "obj_tensionbar"@3210
pushi.e -5
pushi.e 212
pop.v.s [array]global.__objectNames
push.s "obj_whiteedge"@3211
pushi.e -5
pushi.e 213
pop.v.s [array]global.__objectNames
push.s "obj_forest_area5_puzzle"@3212
pushi.e -5
pushi.e 214
pop.v.s [array]global.__objectNames
push.s "obj_forestmaze_controller"@3213
pushi.e -5
pushi.e 215
pop.v.s [array]global.__objectNames
push.s "obj_tempblock_room"@3214
pushi.e -5
pushi.e 216
pop.v.s [array]global.__objectNames
push.s "obj_suitspuzz"@3215
pushi.e -5
pushi.e 217
pop.v.s [array]global.__objectNames
push.s "obj_suitspuzz_button"@3216
pushi.e -5
pushi.e 218
pop.v.s [array]global.__objectNames
push.s "obj_pushableblock"@3217
pushi.e -5
pushi.e 219
pop.v.s [array]global.__objectNames
push.s "obj_glowtile"@3218
pushi.e -5
pushi.e 220
pop.v.s [array]global.__objectNames
push.s "obj_blocktile"@3219
pushi.e -5
pushi.e 221
pop.v.s [array]global.__objectNames
push.s "obj_glowtilepuzz"@3220
pushi.e -5
pushi.e 222
pop.v.s [array]global.__objectNames
push.s "obj_darkeyepuzzle_switch"@3221
pushi.e -5
pushi.e 223
pop.v.s [array]global.__objectNames
push.s "obj_darkeyepuzzle"@3222
pushi.e -5
pushi.e 224
pop.v.s [array]global.__objectNames
push.s "obj_dicebul"@3223
pushi.e -5
pushi.e 225
pop.v.s [array]global.__objectNames
push.s "obj_heartblcon"@3224
pushi.e -5
pushi.e 226
pop.v.s [array]global.__objectNames
push.s "obj_clubsbullet"@3225
pushi.e -5
pushi.e 227
pop.v.s [array]global.__objectNames
push.s "obj_clubsbullet_dark"@3226
pushi.e -5
pushi.e 228
pop.v.s [array]global.__objectNames
push.s "obj_dbullet_maker"@3227
pushi.e -5
pushi.e 229
pop.v.s [array]global.__objectNames
push.s "obj_dbullet_vert"@3228
pushi.e -5
pushi.e 230
pop.v.s [array]global.__objectNames
push.s "obj_heartshaper"@3229
pushi.e -5
pushi.e 231
pop.v.s [array]global.__objectNames
push.s "obj_spinheart"@3230
pushi.e -5
pushi.e 232
pop.v.s [array]global.__objectNames
push.s "obj_dbulletcontroller"@3231
pushi.e -5
pushi.e 233
pop.v.s [array]global.__objectNames
push.s "obj_monsterparent"@3232
pushi.e -5
pushi.e 234
pop.v.s [array]global.__objectNames
push.s "obj_ralseibullet"@3233
pushi.e -5
pushi.e 235
pop.v.s [array]global.__objectNames
push.s "obj_dummyenemy"@3234
pushi.e -5
pushi.e 236
pop.v.s [array]global.__objectNames
push.s "obj_ralseienemy"@3235
pushi.e -5
pushi.e 237
pop.v.s [array]global.__objectNames
push.s "obj_placeholderenemy"@3236
pushi.e -5
pushi.e 238
pop.v.s [array]global.__objectNames
push.s "obj_chain_of_hell"@3237
pushi.e -5
pushi.e 239
pop.v.s [array]global.__objectNames
push.s "obj_chainking"@3238
pushi.e -5
pushi.e 240
pop.v.s [array]global.__objectNames
push.s "obj_chainpiece"@3239
pushi.e -5
pushi.e 241
pop.v.s [array]global.__objectNames
push.s "obj_fadechain"@3240
pushi.e -5
pushi.e 242
pop.v.s [array]global.__objectNames
push.s "obj_finalchain"@3241
pushi.e -5
pushi.e 243
pop.v.s [array]global.__objectNames
push.s "obj_king_body"@3242
pushi.e -5
pushi.e 244
pop.v.s [array]global.__objectNames
push.s "obj_growtangle_bouncer"@3243
pushi.e -5
pushi.e 245
pop.v.s [array]global.__objectNames
push.s "obj_nonsolid_growtangle"@3244
pushi.e -5
pushi.e 246
pop.v.s [array]global.__objectNames
push.s "obj_skychain"@3245
pushi.e -5
pushi.e 247
pop.v.s [array]global.__objectNames
push.s "obj_wavechain"@3246
pushi.e -5
pushi.e 248
pop.v.s [array]global.__objectNames
push.s "obj_dknight_slasher"@3247
pushi.e -5
pushi.e 249
pop.v.s [array]global.__objectNames
push.s "obj_rudinnranger"@3248
pushi.e -5
pushi.e 250
pop.v.s [array]global.__objectNames
push.s "obj_jigsawbullet"@3249
pushi.e -5
pushi.e 251
pop.v.s [array]global.__objectNames
push.s "obj_jigsawryenemy"@3250
pushi.e -5
pushi.e 252
pop.v.s [array]global.__objectNames
push.s "obj_checkers_enemy"@3251
pushi.e -5
pushi.e 253
pop.v.s [array]global.__objectNames
push.s "obj_checker_animtest"@3252
pushi.e -5
pushi.e 254
pop.v.s [array]global.__objectNames
push.s "obj_ralseithrown"@3253
pushi.e -5
pushi.e 255
pop.v.s [array]global.__objectNames
push.s "obj_throwralsei"@3254
pushi.e -5
pushi.e 256
pop.v.s [array]global.__objectNames
push.s "obj_throwtarget"@3255
pushi.e -5
pushi.e 257
pop.v.s [array]global.__objectNames
push.s "obj_checkers_leap"@3256
pushi.e -5
pushi.e 258
pop.v.s [array]global.__objectNames
push.s "obj_ponman_appear"@3257
pushi.e -5
pushi.e 259
pop.v.s [array]global.__objectNames
push.s "obj_ponman_enemy"@3258
pushi.e -5
pushi.e 260
pop.v.s [array]global.__objectNames
push.s "obj_heartbomb_blast"@3259
pushi.e -5
pushi.e 261
pop.v.s [array]global.__objectNames
push.s "obj_suitbomb"@3260
pushi.e -5
pushi.e 262
pop.v.s [array]global.__objectNames
push.s "obj_joker_body"@3261
pushi.e -5
pushi.e 263
pop.v.s [array]global.__objectNames
push.s "obj_centerscythe"@3262
pushi.e -5
pushi.e 264
pop.v.s [array]global.__objectNames
push.s "obj_laserscythe"@3263
pushi.e -5
pushi.e 265
pop.v.s [array]global.__objectNames
push.s "obj_bigscythe"@3264
pushi.e -5
pushi.e 266
pop.v.s [array]global.__objectNames
push.s "obj_carouselbullet"@3265
pushi.e -5
pushi.e 267
pop.v.s [array]global.__objectNames
push.s "obj_joker_teleport"@3266
pushi.e -5
pushi.e 268
pop.v.s [array]global.__objectNames
push.s "obj_spadering"@3267
pushi.e -5
pushi.e 269
pop.v.s [array]global.__objectNames
push.s "obj_rabbick_bush"@3268
pushi.e -5
pushi.e 270
pop.v.s [array]global.__objectNames
push.s "obj_carrotthrower"@3269
pushi.e -5
pushi.e 271
pop.v.s [array]global.__objectNames
push.s "obj_rabbitbullet"@3270
pushi.e -5
pushi.e 272
pop.v.s [array]global.__objectNames
push.s "obj_rabbick_enemy"@3271
pushi.e -5
pushi.e 273
pop.v.s [array]global.__objectNames
push.s "obj_blockbullet_fall"@3272
pushi.e -5
pushi.e 274
pop.v.s [array]global.__objectNames
push.s "obj_bloxer_enemy"@3273
pushi.e -5
pushi.e 275
pop.v.s [array]global.__objectNames
push.s "obj_lancerbike_neo"@3274
pushi.e -5
pushi.e 276
pop.v.s [array]global.__objectNames
push.s "obj_axebullet"@3275
pushi.e -5
pushi.e 277
pop.v.s [array]global.__objectNames
push.s "obj_lancerboss"@3276
pushi.e -5
pushi.e 278
pop.v.s [array]global.__objectNames
push.s "obj_lancerboss2"@3277
pushi.e -5
pushi.e 279
pop.v.s [array]global.__objectNames
push.s "obj_diamondenemy"@3278
pushi.e -5
pushi.e 280
pop.v.s [array]global.__objectNames
push.s "obj_susieenemy"@3279
pushi.e -5
pushi.e 281
pop.v.s [array]global.__objectNames
push.s "obj_lancerboss3"@3280
pushi.e -5
pushi.e 282
pop.v.s [array]global.__objectNames
push.s "obj_king_boss"@3281
pushi.e -5
pushi.e 283
pop.v.s [array]global.__objectNames
push.s "obj_joker"@3282
pushi.e -5
pushi.e 284
pop.v.s [array]global.__objectNames
push.s "obj_clubsenemy"@3283
pushi.e -5
pushi.e 285
pop.v.s [array]global.__objectNames
push.s "obj_clubsenemy_old"@3284
pushi.e -5
pushi.e 286
pop.v.s [array]global.__objectNames
push.s "obj_heartenemy"@3285
pushi.e -5
pushi.e 287
pop.v.s [array]global.__objectNames
push.s "obj_headhathy"@3286
pushi.e -5
pushi.e 288
pop.v.s [array]global.__objectNames
push.s "obj_smallcheckers_enemy"@3287
pushi.e -5
pushi.e 289
pop.v.s [array]global.__objectNames
push.s "obj_pacifyspell"@3288
pushi.e -5
pushi.e 290
pop.v.s [array]global.__objectNames
push.s "obj_deathanim"@3289
pushi.e -5
pushi.e 291
pop.v.s [array]global.__objectNames
push.s "obj_defeatanim"@3290
pushi.e -5
pushi.e 292
pop.v.s [array]global.__objectNames
push.s "obj_healanim"@3291
pushi.e -5
pushi.e 293
pop.v.s [array]global.__objectNames
push.s "obj_oflash"@3292
pushi.e -5
pushi.e 294
pop.v.s [array]global.__objectNames
push.s "obj_rudebuster_anim"@3293
pushi.e -5
pushi.e 295
pop.v.s [array]global.__objectNames
push.s "obj_rudebuster_bolt"@3294
pushi.e -5
pushi.e 296
pop.v.s [array]global.__objectNames
push.s "obj_hypnofx"@3295
pushi.e -5
pushi.e 297
pop.v.s [array]global.__objectNames
push.s "obj_spareanim"@3296
pushi.e -5
pushi.e 298
pop.v.s [array]global.__objectNames
push.s "obj_battleback"@3297
pushi.e -5
pushi.e 299
pop.v.s [array]global.__objectNames
push.s "obj_spellphase"@3298
pushi.e -5
pushi.e 300
pop.v.s [array]global.__objectNames
push.s "obj_battleblcon"@3299
pushi.e -5
pushi.e 301
pop.v.s [array]global.__objectNames
push.s "obj_endbattle"@3300
pushi.e -5
pushi.e 302
pop.v.s [array]global.__objectNames
push.s "obj_growtangle"@3301
pushi.e -5
pushi.e 303
pop.v.s [array]global.__objectNames
push.s "obj_dmgwriter"@3302
pushi.e -5
pushi.e 304
pop.v.s [array]global.__objectNames
push.s "obj_heart"@3303
pushi.e -5
pushi.e 305
pop.v.s [array]global.__objectNames
push.s "obj_shop1"@3304
pushi.e -5
pushi.e 306
pop.v.s [array]global.__objectNames
push.s "obj_shop2"@3305
pushi.e -5
pushi.e 307
pop.v.s [array]global.__objectNames
push.s "DEVICE_APPEARANCE"@3306
pushi.e -5
pushi.e 308
pop.v.s [array]global.__objectNames
push.s "DEVICE_CHOICE"@3307
pushi.e -5
pushi.e 309
pop.v.s [array]global.__objectNames
push.s "DEVICE_CONTACT"@3308
pushi.e -5
pushi.e 310
pop.v.s [array]global.__objectNames
push.s "DEVICE_FAILURE"@3309
pushi.e -5
pushi.e 311
pop.v.s [array]global.__objectNames
push.s "DEVICE_GONERMAKER"@3310
pushi.e -5
pushi.e 312
pop.v.s [array]global.__objectNames
push.s "DEVICE_MENU"@3311
pushi.e -5
pushi.e 313
pop.v.s [array]global.__objectNames
push.s "DEVICE_OBACK_4"@3312
pushi.e -5
pushi.e 314
pop.v.s [array]global.__objectNames
push.s "PROCESS_LOGO"@3313
pushi.e -5
pushi.e 315
pop.v.s [array]global.__objectNames
push.s "PROCESS_DOG"@3314
pushi.e -5
pushi.e 316
pop.v.s [array]global.__objectNames
push.s "obj_credits"@3315
pushi.e -5
pushi.e 317
pop.v.s [array]global.__objectNames
push.s "obj_dkris_event"@3316
pushi.e -5
pushi.e 318
pop.v.s [array]global.__objectNames
push.s "obj_darkphone_event"@3317
pushi.e -5
pushi.e 319
pop.v.s [array]global.__objectNames
push.s "obj_time"@3318
pushi.e -5
pushi.e 320
pop.v.s [array]global.__objectNames
push.s "obj_move_to_point"@3319
pushi.e -5
pushi.e 321
pop.v.s [array]global.__objectNames
push.s "obj_legend"@3320
pushi.e -5
pushi.e 322
pop.v.s [array]global.__objectNames
push.s "obj_savemenu"@3321
pushi.e -5
pushi.e 323
pop.v.s [array]global.__objectNames
push.s "obj_initializer2"@3322
pushi.e -5
pushi.e 324
pop.v.s [array]global.__objectNames
push.s "obj_overworldc"@3323
pushi.e -5
pushi.e 325
pop.v.s [array]global.__objectNames
push.s "obj_mainchara"@3324
pushi.e -5
pushi.e 326
pop.v.s [array]global.__objectNames
push.s "obj_sdl"@3325
pushi.e -5
pushi.e 327
pop.v.s [array]global.__objectNames
push.s "obj_sdr"@3326
pushi.e -5
pushi.e 328
pop.v.s [array]global.__objectNames
push.s "obj_sul"@3327
pushi.e -5
pushi.e 329
pop.v.s [array]global.__objectNames
push.s "obj_sur"@3328
pushi.e -5
pushi.e 330
pop.v.s [array]global.__objectNames
push.s "obj_soliddark"@3329
pushi.e -5
pushi.e 331
pop.v.s [array]global.__objectNames
push.s "obj_sur_dark"@3330
pushi.e -5
pushi.e 332
pop.v.s [array]global.__objectNames
push.s "obj_sdl_dark"@3331
pushi.e -5
pushi.e 333
pop.v.s [array]global.__objectNames
push.s "obj_solidenemy"@3332
pushi.e -5
pushi.e 334
pop.v.s [array]global.__objectNames
push.s "obj_solidenemy_2"@3333
pushi.e -5
pushi.e 335
pop.v.s [array]global.__objectNames
push.s "obj_solidblock"@3334
pushi.e -5
pushi.e 336
pop.v.s [array]global.__objectNames
push.s "obj_solidlong"@3335
pushi.e -5
pushi.e 337
pop.v.s [array]global.__objectNames
push.s "obj_solidcircle"@3336
pushi.e -5
pushi.e 338
pop.v.s [array]global.__objectNames
push.s "obj_diag"@3337
pushi.e -5
pushi.e 339
pop.v.s [array]global.__objectNames
push.s "obj_diamond"@3338
pushi.e -5
pushi.e 340
pop.v.s [array]global.__objectNames
pushglb.v global.__objectDepths
call.i array_length_1d(argc=1)
pop.v.v local.len
call.i @@NewGMLArray@@(argc=0)
pop.v.v global.__objectID2Depth
pushi.e 0
pop.v.i local.i

:[1]
pushloc.v local.i
pushloc.v local.len
cmp.v.v LT
bf [end]

:[2]
pushi.e -5
pushloc.v local.i
conv.v.i
push.v [array]global.__objectNames
call.i asset_get_index(argc=1)
pop.v.v local.objID
pushloc.v local.objID
pushi.e 0
cmp.i.v GTE
bf [4]

:[3]
pushi.e -5
pushloc.v local.i
conv.v.i
push.v [array]global.__objectDepths
pushi.e -5
pushloc.v local.objID
conv.v.i
pop.v.v [array]global.__objectID2Depth

:[4]
push.v local.i
push.e 1
add.i.v
pop.v.v local.i
b [1]

:[end]